### ISSUE TITLE
ZippCast Videos Won't Upload

### ISSUE THREAD

**Issue by dkl3** [bibanon/tubeup#1]
Hi, I've been trying to upload ZippCast videos to the Internet Archive. However, this error happens: http://pastebin.com/faNdK9TE. I was told because ZippCast doesn't record the upload date.

I'd love if this error could be fixed, thanks.

**Comment by antonizoon** [comment]
Unfortunately, ZippCast is poorly designed, and the extractor spits out inconsistent JSON. Can't fix from here.

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/zippcast.py

**Comment by vxbinaca** [comment]
@dkl3 Have you reported this issue to Youtube-dl? This would seem like a problem on their end.

**Comment by dkl3** [comment]
No, I haven't (and sorry for not getting the message sooner).
