### ISSUE TITLE
twitch: Skip live broadcasts

### ISSUE THREAD

**Issue by mat8913** [bibanon/tubeup#104]
Running tubeup on a past-broadcasts url (ie. https://www.twitch.tv/USERNAME/videos/past-broadcasts) will download the currently broadcasting stream if there is one. This is a problem because it wont download the complete stream. In my opinion, it would be better to wait for the stream to finish before beginning downloading.

As tubeup uses youtube-dl for this, I reported the issue at ytdl-org/youtube-dl#22634 and got the advice to call youtube-dl with `--match-filter '!is_live'`. Would it be possible to configure tubeup to use this option?

**Comment by vxbinaca** [comment]
You could wait for the stream to process on Twitch.

**Comment by vxbinaca** [comment]
I'm on the fence about this one. On one hand if this works, and I have not tested it quite yet, this would prevent a issue I've known about for a while but on the other it prevents downloading of something and we may get issues posted bitching someone couldn't download a livestream.

**Comment by brandongalbraith** [comment]
@vxbinaca My two cents is its better to grab something incomplete than to block on something live and miss something a user wanted that might be unavailable in the future.

**Comment by vxbinaca** [comment]
@brandongalbraith Here's the way VODs are processed:

In chunks, that their hardware slowly processes and sometimes depending on the length of the stream or if the stream image changed a lot (gaming) it may take up to 6 hours or more for a livestream VOD to process. Youtube is much faster at under a hour usually to process a 2 hour stream.

The flag would be easy to implement, however here's how I avoid the problem:

Rip a video 6 hours after it stopped streaming, attempt a test rip. FFMPEG will dump a bunch of color text into the terminal if theres a problem.

**Comment by brandongalbraith** [comment]
I think we could implement the flag where we loop and check the API every X number of seconds, and only begin retrieval once the content is no longer live. I'm not familiar with Twitch though; does the API return a value that confirms that the stream is no longer live and the content you're retrieving is the final rendition?

**Comment by vxbinaca** [comment]
Why not let youtube-dl do it instead of us. I'll test the flag when I have time this week.

**Comment by brandongalbraith** [comment]
@vxbinaca I'm revisiting this. I've come to the opinion that if the twitch stream is live, tubeup should avoid it (and if you absolutely want to rip it live, grab it with ytdl), while we should grab and upload if it's not live. This should avoid uploading incomplete twitch rips to IA. 

Any reason this doesn't make sense?

**Comment by vxbinaca** [comment]
No Brandon you need to wait until YTDL fix Twitch channel extraction it literally broke within the last week. So once that's fixed then it can be tested. single vidoes work but Twitch changed their API and how channel URLs are handled, currently the extractor doesn't parse the channels properly.

Thanks for looking into this.

**Comment by brandongalbraith** [comment]
Ahh, wasn't aware YTDL recently broke Twitch extraction. Thanks Paul 👍 , I'll wait for their fix to drop.

**Comment by vxbinaca** [comment]
One thing to watch out for is even if a video isn't live, the way twitch works is they make the video live immediately but still process it, so it comes in in chunks until it's done processing. I'm not sure but it seems like you could rip a video thats not live but not done processing and only get part of it. This is something I trill run into and have simply picked a time early in the morning when there are typically no broadcasters on AND theres no in-process videos, everything ready to go and the previous days streams can be ripped form all targets in a few hours.

**Comment by vxbinaca** [comment]
@brandongalbraith Youtube-dl pushed out TWO versions today and neither had any of the Twitch PRs merged in. All Twitch channel rips will cease until it's fixed, which may be months. I might have to pull URLs from my targets.

**Comment by brandongalbraith** [comment]
@vxbinaca If you know the last version of YTDL that did work for you, I can bake a Docker container pinned to that version but using the most recent version of tubeup.

**Comment by vxbinaca** [comment]
> @vxbinaca If you know the last version of YTDL that did work with Twitch, I can bake a Docker container pinned to that version but using the most recent version of tubeup. Let me know!

No that won't work because it's a URL scheme change in the latest API. YTDL needs to accept the PRs that fix channel URLs for Twitch for this to work. So we have to wait on them. In the meantime since my scripts use Twitch channel URLs and not individual URLs that do work (this would be a pain to do), all Twitch ingestion has stopped until a version is pushed that fixes this bug.

**Comment by brandongalbraith** [comment]
Thanks for letting me know, might be time for us to run our own fork of
YTDL 🤷🏻‍♂️

**Comment by vxbinaca** [comment]
I don't think you want to take on that administrative responsibility because of a single extractor that they're dragging their feet on accepting a PR on. This is coming from someone who is a completionist and wants to get everything from a target and automate it. It's a problem that can wait. Youtube is the priority and what the majority of both YTDL and Tubeups users care about, and they're very attentive to ensuring YT works.

**Comment by vxbinaca** [comment]
I emailed DTFSW so let's see where this goes, likely nowhere I predict. We may have to end up forking and using our own custom youtube-dl to get Twitch channel compatibility for the rest of the users.

**Comment by vxbinaca** [comment]
I'm about ready to form youtube-dl, their entire source tree and PRs, and make no substantive code changes myself, but just start mergin' PRs, then call it vid-dl and make a pypi upload for it, then reply to all their stale ass non-merged PRs sitting there with a link to the bug fixed version of the program.

**Comment by vxbinaca** [comment]
I'm going to be testing for this tonight. I had to write custom scripts to pull in extractor fixes the YTDL guys are just sitting on, and inject a custom version over my locally installed version, but it should work. I'm going to test this proposed flag in a bit.

**Comment by vxbinaca** [comment]
Well we're at the end of the road on this one boyos. YTDL guys aren't merging #25606 so we can't do shit until then, and the hacky directions in the thread to manually inject the fixed extractor into a YTDL install aren't working for me.

So this is it. Closing. OP just wait 6 hours to do a rip on a URL so it processes the video. That's the best solution I can give you.
