### ISSUE TITLE
Vimeo: incorrect upload date for embed-only videos

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#107]
Example video: https://player.vimeo.com/video/352598405
It doesn't exist under https://vimeo.com/352598405

There is no "upload_date" in the info.json file and the archive.org item metadata publish date is set to the upload date of the item.

**Comment by vxbinaca** [comment]
Closing because this isn't our bug. It's a YouTube-dl extractor for Vimeo issue not a Tubeup issue. Report to them. Upgrade your binary as well using pythons pip.
