### ISSUE TITLE
Add option to overwrite existing items

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#108]
I wanted to replace an existing ia item, but it seems like tubeup only adds files - it won't remove existing ones or replace the item metadata (or seemingly change the item metadata at all). There doesn't seem to be a way to fully delete an IA item to "start from scratch", so I'm asking here.

**Comment by vxbinaca** [comment]
`ia delete [IDENTIFIER] -H x-archive-keep-old-version:0`

This will irrevocably delete the contents of a item, specifically what does this is the `-H x-archive-keep-old-version:0' part. So test whether the video is still live or not. 

The items metadata must be hand edited to be changed. The .JSON file will be replaced on re-rip.
