### ISSUE TITLE
Add option to skip existing items

### ISSUE THREAD

**Issue by FailedShack** [bibanon/tubeup#109]
Sometimes while processing a list of videos I'll run into the case where another archive.org user has already uploaded the same video, so tubeup will fail because I don't have permission to update the item. Unfortunately, this aborts the entire queue.

Attempting to run tubeup again with the same list, even if you exclude the problematic video, will have it redownload any videos that had already been successfully uploaded, wasting time and bandwidth.

I believe there should be flag that allows tubeup to check if an item exists before it downloads anything. As it stands, you end up having to run tubeup for each video separately.

**Comment by brandongalbraith** [comment]
I would be amiable to accepting a pull request for this feature (performing a lookup for an item prior to an upload attempt). Otherwise, I'll get to it eventually, hasn't been a priority as my tooling wraps error handling around tubeup.

**Comment by vxbinaca** [comment]
>Attempting to run tubeup again with the same list, even if you exclude the problematic video, will have it redownload any videos that had already been successfully uploaded, wasting time and bandwidth.

Add `--use-download-archive' next time and keep a better eye on your rips. Don't just dump a channel and go off and do something else. Also use a VPS to rip not your home machine.

So what you want is based on [extractor]-[videoID], to search for every video in a channel you dump? Couldn't you just:

`youtube-dl --get-id [CHANNEL] > CHANNEL.txt`

Then just prepend a command to each line that has a videoID on it then `sh` that? It rips the vids one by one, if it encounters a item thats already been created then just down't upload it. Once that script is done you just delete the cache. As the script goes through it pulls from the cache until done, or if you don't have a cache because you haven't ripped the channel yet then it just download and upload one at a time.

**Comment by FailedShack** [comment]
That is a possible workaround, but point still stands that you're running tubeup for each video separately, which kind of defeats the purpose of being able to queue multiple videos to upload at once. Tubeup should be able to handle this gracefully.

I'll keep `--use-download-archive` in mind though, thanks.

**Comment by vxbinaca** [comment]
The functionality you ask for is entirely too complex and would require maintane if something changed with YTDL or IA. No way, unless you not only submit that functionality and also maintain it in the future.

**Comment by brandongalbraith** [comment]
This has been on my mind for some time. Opening back up to continue work on this feature.

Command line functionality to replicate with switch prior to starting artifact retrieval: `ia metadata <identifier> --exists`

**Comment by vxbinaca** [comment]
You'd have to replicate this for channels too. But go for it. Your code is super sound but I'm going to extensively test the feature.

**Comment by brandongalbraith** [comment]
So the good news is that we're likely to get false negatives instead of false positives (a search occurs for an item by identifier, but for whatever reason the item was previously uploaded and the identifiers don't match so the item's digital artifacts are uploaded again). With that said, I'd hate for IA to waste space needlessly, so I might explore further reconciliation efforts such as using sha1 hashes of digital artifacts (which can be enumerated from item metadata with the ia python client). Maybe they do pruning or deduplication internally using cryptographic hashes, I'd have to check with patron services.

**Comment by vxbinaca** [comment]
Please leave me a option to turn this off with a flag. Thanks again for your work.

**Comment by MisterSheeple** [comment]
Bump for this. I've tried processing playlists and it would be nice if it could just keep going if it finds an existing item, rather than outright stopping once it finds an item that can't be uploaded.

**Comment by brandongalbraith** [comment]
@MisterSheeple I have to check with the Internet Archive Patron Services how to do a robust search for an existing item prior to the youtube-dl retrieval step. Stay tuned!

**Comment by vxbinaca** [comment]
> Bump for this. I've tried processing playlists and it would be nice if it could just keep going if it finds an existing item, rather than outright stopping once it finds an item that can't be uploaded.

Split out the playlist as individual video IDs in a file, use vim to make a batch file that rips each one one at a time.

**Comment by brandongalbraith** [comment]
Revisiting this. 

Searching for items won't work, as the Internet Archive is suppressing MirrorTube results as an anti-spam measure. We could attempt to derive an item identifier from the URL of the to-be-archived item, attempt to retrieve the item page from archive.org (`curl https://archive.org/details/youtube-<video_ID>`, for example), and action accordingly.

**Comment by brandongalbraith** [comment]
@jjjake sorry for the bump, I wanted to check if `ia metadata <item_identifier>` was an expensive API operation on the server side for IA (the intent is to check if an item exists before performing an archival operation). If it _is_ expensive, is there a more preferred method for quickly checking if an item already exists?

**Comment by johtso** [comment]
@brandongalbraith was initially going to suggest just making a HEAD request to the item page URL, but actually it would probably make more sense to check multiple items using the advanced search API.

Something like this: `https://archive.org/advancedsearch.php?q=identifier%3Anature0030unse+OR+identifier%3Awonderfulwizardo00baumiala&fl%5B%5D=identifier&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=callback&save=yes`

Not sure if there's a limit to the size of the query, but would be quite easy to test.

**Comment by johtso** [comment]
I feel like there's 2 different issues here.
1. avoiding archiving things that have already been archived.
2. being able to resume an archive of a channel by just running the job again and have it ignore things that have already been uploaded.

I was a little surprised that when I reran a job for a specific video it would just do everything again, even uploading the video file to the existing IA item again unnecessarily.

**Comment by brandongalbraith** [comment]
1. If you don't own the item in IA, tubeup will download all of the digital artifacts and then attempt to upload them. tubeup will error out on the first item when IA returns "access denied". We should detect if the item exists and if it is owned by your user. If it is not owned by you, we shouldn't attempt to download (as you're doing to waste compute and bandwidth fetching content you can't upload).
2. If you _do_ own the item, the use case is a previous upload attempt might have partially succeeded; for example, consider uploading an item and your internet connection drops or the IA storage node you're uploading to becomes unavailable. We would throw an information message that the item already exists, but still attempt to upload to push digital artifacts that were missed on the first upload.

**Comment by FailedShack** [comment]
> @brandongalbraith was initially going to suggest just making a HEAD request to the item page URL, but actually it would probably make more sense to check multiple items using the advanced search API.
> 
> Something like this:
> 
> ```
> https://archive.org/advancedsearch.php?q=identifier%3Anature0030unse+OR+identifier%3Awonderfulwizardo00baumiala&fl%5B%5D=identifier&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=callback&save=yes
> ```
> 
> Not sure if there's a limit to the size of the query, but would be quite easy to test.

The former is how I ended up doing it in the shell script I currently use:
https://gist.github.com/FailedShack/48b54c303cf297b3bb28c1190ce1892d

**Comment by johtso** [comment]
Ah, I see we're not using the `checksum` option when uploading items, we probably should be right?

**Comment by brandongalbraith** [comment]
@johtso Good catch! We should definitely be using checksums to skip files that have already been upload. `--skip-existing`, I'm not so sure about, as just because a filename exists doesn't necessarily mean it's the same file as tubeup might be attempting to upload, so we want to error on the side of caution in that regard.

https://archive.org/services/docs/api/internetarchive/quickstart.html?highlight=checksum

**Comment by vxbinaca** [comment]
Checksum will upload the metadata still since the file changed, some things will still be uploaded but it's tiny and won't matter.

**Comment by brandongalbraith** [comment]
@vxbinaca Checksum calculates the md5 checksum of each local file and skips files where the md5 checksum of the file matches what checksum of the file at IA.

**Comment by johtso** [comment]
Hmm.. I've just tried running the same task for the same video multiple times with the checksum option enabled, and it still uploads the whole video.

Does the checksum of the video possibly change every time it's downloaded?

**Comment by vxbinaca** [comment]
> I feel like there's 2 different issues here.
> 
> 1. avoiding archiving things that have already been archived.

Fixing that is difficult without being abusive to IA.

> 2. being able to resume an archive of a channel by just running the job again and have it ignore things that have already been uploaded.
> 
> I was a little surprised that when I reran a job for a specific video it would just do everything again, even uploading the video file to the existing IA item again unnecessarily.

Try `--use-download-archive`. Really.

**Comment by upintheairsheep2** [comment]
> Sometimes while processing a list of videos I'll run into the case where another archive.org user has already uploaded the same video, so tubeup will fail because I don't have permission to update the item. Unfortunately, this aborts the entire queue.
> 
> Attempting to run tubeup again with the same list, even if you exclude the problematic video, will have it redownload any videos that had already been successfully uploaded, wasting time and bandwidth.
> 
> I believe there should be flag that allows tubeup to check if an item exists before it downloads anything. As it stands, you end up having to run tubeup for each video separately.

I agree. It’s so f**king annoying

**Comment by vxbinaca** [comment]
@brandongalbraith Jake just updated the search function to use less traffic. Perhaps revisiting this and the version bug with IA would be wise?

When you get a moment of course. Thanks.
