### ISSUE TITLE
Define an item identifier

### ISSUE THREAD

**Issue by FailedShack** [bibanon/tubeup#110]
I know this is just a blatant duplicate of #80, but I couldn't comment there so I had to open a new issue.

I understand that this feature is not currently present to avoid users uploading items that have been removed due to formal take-down requests. However, I ran into an issue while processing a lengthy video list, where tubeup failed partway through one of the uploads.
Restarting it caused it to start uploading them in a different order and it wasn't clear to me that the upload would eventually be filled in properly, so I removed the item from my profile to re-create it from scratch. However, once it got back to it, it then failed with `Access Denied - This item has been taken offline`.  In hindsight, the proper course of action would have been to follow the advice presented in #108 instead.

It appears archive.org does not differentiate between a self-removal and a formal take-down. The former may be performed by any user from their profile page, rendering identifiers unusable. So I believe one should be able exceptionally use a different identifier (by appending an underscore at the end, for example).

**Comment by brandongalbraith** [comment]
I would prefer the course of action be reaching out to Internet Archive staff to free up the identifier versus allowing free form item identifiers; having them be deterministic whenever possible prevents possible duplicates, and saves space on IA Petaboxes.

For future reference, if an upload fails and is restarted, tubeup should only re-attempt files for an item that were not already successfully uploaded; failed files will be re-attempted automatically.

**Comment by vxbinaca** [comment]
Rip videos one at a time, see your other issue #109. If you need help with the VIM commands ask to ease doing it ask.

Archive.org doesn't want multiple uploads, and neither do I. Closing.
