### ISSUE TITLE
Adapting this script for uploading previously archived Youtube channels

### ISSUE THREAD

**Issue by nihelmasell** [bibanon/tubeup#113]
Hi, sorry if this questions is off-topic. I have terabytes of Youtube channels which I would like to send to the Archive, without downloading them again. Is there an easy way to edit this script for that end? Thanks in advance

**Comment by vxbinaca** [comment]
Yes your preferred text editor and a pull request.

**Comment by vxbinaca** [comment]
Not to mention, I can guarantee you didn't get the metadata we require in the formats tubeup requires, and the filenames don't match. It's not just a video uploader. It preserves the metadata. Without that metadata it can't make the item.

**Comment by nihelmasell** [comment]
> Not to mention, I can guarantee you didn't get the metadata we require in the formats tubeup requires, and the filenames don't match. It's not just a video uploader. It preserves the metadata. Without that metadata it can't make the item.

This is the formula I use 

youtube-dl --force-ipv4 --ignore-errors --ignore-config --no-continue --no-overwrites --retries 100 --write-info-json --write-annotations -f bestvideo+bestaudio -o '/Volumes/WD-10TB-DIC2019/Youtube/Computerphile/%(title)s.%(ext)s' --download-archive /Volumes/WD-10TB-DIC2019/Youtube/Computerphile/archive.txt --write-description --write-thumbnail --write-sub --write-auto-sub --sub-format "srt" --sub-lang es,en,de,fr --add-metadata --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M" https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA

I just don’t know how to edit the script. I mean, I don’t know python. But I want to have all that stuff archived externally, in case my home gets burned or robbed.

**Comment by vxbinaca** [comment]
You need to remove ASCII (convert spaces to underscores) from your filenames that's what you're missing but a one liner can fix that. That'll fuck your shit up immediately if you don't fix that.

UPGRADE ALL YOUR BINARIES/FFMPEG BEFORE YOU DO ANYTHING:

`sudo pip3 install -U youtube-dl tubeup internetarchive pip ; sudo apt update ; sudo apt upgrade ffmpeg`

list out the files, get the video IDs from each filename (can be done with VIM), 

then toss all your files into ~/.tubeup/downloads

Run your batch file, should start uploading everything. Alternatively you can figure out which channels you did, get their video IDs (`--get-id' in ytdl), and make a batch file that way. You'd still have to

**Comment by nihelmasell** [comment]
> You need to remove ASCII (convert spaces to underscores) from your filenames that's what you're missing but a one liner can fix that. That'll fuck your shit up immediately if you don't fix that.
> 
> UPGRADE ALL YOUR BINARIES/FFMPEG BEFORE YOU DO ANYTHING:
> 
> `sudo pip3 install -U youtube-dl tubeup internetarchive pip ; sudo apt update ; sudo apt upgrade ffmpeg`
> 
> list out the files, get the video IDs from each filename (can be done with VIM),
> 
> then toss all your files into ~/.tubeup/downloads
> 
> Run your batch file, should start uploading everything. Alternatively you can figure out which channels you did, get their video IDs (`--get-id' in ytdl), and make a batch file that way. You'd still have to copy all your files into ~/.tubeup/downloads though.
> 
> Edit: Why aren't you getting all subs instead of those specified languages? You'd miss Thai or any other asian language.

I have an archive.txt file in each directory (which corresponds to a channel) having all the IDs of the videos (I think they are also written into the metadata files; I’m gonna look up online how to extract that to match it with the videos). // Which sort of files should be inside the downloads directory? Can you give me an example of the naming conventions and quantity of files for each video? 

I tried downloading all languages. The problem is some channels have 30,000 videos, which overpopulate my folders, and complicate the future viewing of them (having to choose between 100 languages in mpv/VLC). So I choose the languages I understand (and the most populars in the world I think). I wish I had a further understanding of bash and python. But hoarding stuff takes all my time.

**Comment by vxbinaca** [comment]
>The problem is some channels have 30,000 videos, which overpopulate my folders,

Talk to Internet Archive before doing a upload that large.

**Comment by nihelmasell** [comment]
> > The problem is some channels have 30,000 videos, which overpopulate my folders,
> 
> Talk to Internet Archive before doing a upload that large.

No, that was my answer to your question on why I select only some languages. I only upload selected stuff to the IA, which has an IP blocking/bandwidth limiting btw. Is there an easy way to convert my files to your program? The IA knows very well how to protect themselves.

**Comment by antonizoon** [comment]
@nihelmasell So actually your needs are pretty simple. What you need to do is program a script that generates a list from a channel or playlist using youtube-dl, then check if the videos already exist on the internet archive API perhaps using the pip internetarchive library: http://pypi.python.org/pypi/internetarchive

Then it should return only a list of videos that are not on the internet archive, which can be passed to tubeup.

It's a pretty simple set of code but I got other things to do unfortunately,.
