### ISSUE TITLE
Youtube-dl issue when filenames are too long.

### ISSUE THREAD

**Issue by jjjake** [bibanon/tubeup#116]
It seems that there is an issue downloading files with `youtube-dl` when the filenames are too long. This seems to be pretty common with Twitter videos.

Here's an example:

```
tubeup https://twitter.com/greg_doucette/status/1268231604461342720
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: none
[debug] Proxy map: {}
There are no annotations to write.
ERROR: Cannot write metadata to JSON file /home/user/.tubeup/downloads/T._Greg_Doucette_-_1_9_8_Columbus_OH_-_more_police_destroying_private_property_without_due_process_Can_you_imagine_how_small_your_must_be_to_have_all_that_body_armor_and_guns_and_still_be_afraid_of_water_bottles_Yikes-1268231604461342720.info.json
Traceback (most recent call last):
  File "/home/user/venv3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1850, in process_info
    write_json_file(self.filter_requested_info(info_dict), infofn)
  File "/home/user/venv3/lib/python3.5/site-packages/youtube_dl/utils.py", line 1828, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/home/user/venv3/lib/python3.5/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/user/venv3/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: '/home/user/.tubeup/downloads/T._Greg_Doucette_-_1_9_8_Columbus_OH_-_more_police_destroying_private_property_without_due_process_Can_you_imagine_how_small_your_must_be_to_have_all_that_body_armor_and_guns_and_still_be_afraid_of_water_bottles_Yikes-1268231604461342720.info.json.vudd9hyj.tmp'
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/user/venv3/lib/python3.5/site-packages/tubeup/__main__.py", line 93, in main
    use_download_archive):
  File "/home/user/venv3/lib/python3.5/site-packages/tubeup/TubeUp.py", line 361, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/user/venv3/lib/python3.5/site-packages/tubeup/TubeUp.py", line 275, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.tubeup/downloads/T._Greg_Doucette_-_1_9_8_Columbus_OH_-_more_police_destroying_private_property_without_due_process_Can_you_imagine_how_small_your_must_be_to_have_all_that_body_armor_and_guns_and_still_be_afraid_of_water_bottles_Yikes-1268231604461342720.info.json'
```

Any suggestions on how to resolve this? I'd suggest we change the output format. Maybe just keep it simple, like `"%(id)s.%(ext)s"`, since we have all of the metadata in the item?

**Comment by jjjake** [comment]
I actually like the idea of simply exposing `--output`, so the user can select their own output template. I'll submit a PR.

**Comment by jjjake** [comment]
Shoot, I forgot that I had write access to this repository.

I meant for 14a4890a85208a2c57c43c33364713cd1d2faa1e to be a PR. Please let me know if you'd like me to revert it. Sorry about that!

**Comment by brandongalbraith** [comment]
@jjjake I have a preference for defaulting to the template you provided (this is already done for Facebook content, for example). Not against exposing templating to the user, but I think strong opinions are warranted considering the global namespace where this content ends up.

**Comment by jjjake** [comment]
Alright, here's a PR that changes the default template to `%(id)s.%(ext)s`: https://github.com/bibanon/tubeup/pull/117

**Comment by brandongalbraith** [comment]
@jjjake LGTM 👍  @antonizoon or @vxbinaca Clear to merge this up?

**Comment by vxbinaca** [comment]
Didn't we discuss that this was a extractor issue of dumping the post as the title, and that the extractors on YTDLs end should be cleaned up?

**Comment by vxbinaca** [comment]
Okay let's slay each PR dragon and I'll do final tests and push to pypi.

**Comment by vxbinaca** [comment]
Note: I'm essential during the pandemic, and I only opened Github to check is theres a new Swiss release (Gamecube), new Ralim soldering iron firmware and if theres a bug report for why Twitch stopped extracting this afternoon with youtube-dl (410: Gone for all channels).

I'll slice out time this weekend to tubeup.0

**Comment by vxbinaca** [comment]
Heres an idea, if length is a limit why not truncate the name being given from the extractor after 180 characters? That should be plenty to avoid any errors.

**Comment by brandongalbraith** [comment]
@vxbinaca Personal opinion is to merge the PR @jjjake now, since anyone using tubeup is blocked from getting current events content into IA from places like Twitter, and we can revisit the architecture (fixing YTDL extractors) post pandemic riots. You're not wrong! Just saying a quick fix is in order so nothing of value from this moment is lost to time.

Noted that you are essential and latency in responses is to be expected. Thanks for jumping in here.

**Comment by vxbinaca** [comment]
Merging until we can find a better solution.

**Comment by vxbinaca** [comment]
She's live, boys.

**Comment by brandongalbraith** [comment]
Thank you @vxbinaca 🙏 Already have a fix in mind to set the output template in config file, I’ll also put effort into getting the YTDL extractor fixed.

**Comment by vxbinaca** [comment]
@brandongalbraith No need, @jjjake added a way to specify output template. I just need to figure out how it works if it's like I think it is, then mass-edit my scripts (can do with one-liner), sync changes to my repo and I'll be [back in business until the next bug](https://www.youtube.com/watch?v=Fn37Ur6nbG4)

**Comment by vxbinaca** [comment]
And we'll have to be reverting that UTF-8 fix I think
