### ISSUE TITLE
Incorrect title printed to console

### ISSUE THREAD

**Issue by Coloradohusky** [bibanon/tubeup#120]
Uploaded [Star Wars: Squadrons – Official Reveal Trailer](https://www.youtube.com/watch?v=w0eRkhR1z6A), what was printed was `b'Title: Star Wars: Squadrons \xe2\x80\x93 Official Reveal Trailer'`

**Comment by Coloradohusky** [comment]
Doesn't actually affect Internet Archive title, just console output, fyi

**Comment by Coloradohusky** [comment]
Used to work fine, until #106 added `.encode('utf-8')`, and I see that vxbinaca also noticed it, just hasn't been rolled back yet

**Comment by brandongalbraith** [comment]
@vxbinaca Did you happen to push out a new release after reverting #106?

**Comment by vxbinaca** [comment]
No I'm waiting for the other things we're working on to be fixed, this is a low priority bug.

**Comment by vxbinaca** [comment]
I just hand-reverted this @Coloradohusky please test to confirm. It'll be available in the next release.

**Comment by Coloradohusky** [comment]
Works great.
