### ISSUE TITLE
Feature request: Support archiving of YouTube chat replays

### ISSUE THREAD

**Issue by Xalaxis** [bibanon/tubeup#124]
YouTube videos which were originally live streams carry "chat replays", a log of all the chat messages sent.  It would be great if tubeup supported this metadata.  https://github.com/taizan-hokuto/pytchat seems to be a great library for this purpose.

**Comment by vxbinaca** [comment]
Youtube-dl needs too support it. I'm not complicating our code to support a 3rd/4th dependency. Talk to the youtube-dl guys about supporting it, get a flag implemented or have it made as a subtitle and we'll implement that. Updates with YTDL are typically timely especially for the youtube extractor and it's a better fit they do it instead of us having to rely on another project who may not have the speed we require in fixes.

**Comment by Xalaxis** [comment]
Okay, thanks 🙂

**Comment by vxbinaca** [comment]
@Xalaxis If you can get the feature added I'll test and push out a version with the flag to grab the live chat too. Internet Archive can go back later and do whatever. We're just focused on actually grabbing the data.

**Comment by Xalaxis** [comment]
Request created for youtube-dl at https://github.com/ytdl-org/youtube-dl/issues/25874

**Comment by brandongalbraith** [comment]
@Xalaxis Looks like @dstftw insta-closed your issue. That's fine, leave this here and I'll see what the difficulty level is of using the python library you refer to in that issue (https://github.com/taizan-hokuto/pytchat) in tubeup alongside youtube-dl (it looks like it simply renders an html file of the chat contents, so it might be straightforward).

**Comment by Xalaxis** [comment]
@brandongalbraith The issue was closed as "incomplete", which means they think I missed out an important piece of information in the issue.  I'm not sure what that would be, so I'll try and get it re-opened.

As for implementing it here if you want to, I think pytchat also supports a JSON format, which might be more suitable for long-term storage.

**Comment by brandongalbraith** [comment]
@Xalaxis I’m not one to turn away free help. If you can do the legwork to get this functionality added into youtube-dl, that’d be preferable and less brittle long term. It would be of significant value to the youtube-dl user base (IMHO).

**Comment by Xalaxis** [comment]
👍 I agree, especially as they already have support for Twitch VoD chat replays.  I'll push for the issue to be re-opened.

**Comment by vxbinaca** [comment]
> @Xalaxis Looks like @dstftw insta-closed your issue. That's fine, leave this here and I'll see what the difficulty level is of using the python library you refer to in that issue (https://github.com/taizan-hokuto/pytchat) in tubeup alongside youtube-dl (it looks like it simply renders an html file of the chat contents, so it might be straightforward).

The first problem you''re going to run into is site changes that break that specific pychat program. Then we have to wait for them to fix it, or take it on ourself and track their changes and inject our hacks back in. It's a utter nightmare. This is why I like division of labor.

>  I agree, especially as they already have support for Twitch VoD chat replays. I'll push for the issue to be re-opened.

Twitch VoD replays are archived as a JSON, which internet archive can go back and fix by making it apart of the deriving process for items starting with "twitch-vod". They can just convert the JSON to SRT. Thats something that can be done on their end. Whats important is the chats are saved at all. Youtube chats, thats another beast.

He closed your issue because you provided no command lin e output for him to look at. You didn't follow submission guidelines.

**Comment by Xalaxis** [comment]
Issue re-open 🎉 

> Twitch VoD replays are archived as a JSON, which internet archive can go back and fix by making it apart of the deriving process for items starting with "twitch-vod". They can just convert the JSON to SRT. Thats something that can be done on their end. Whats important is the chats are saved at all. Youtube chats, thats another beast.

I'd be surprised if YouTube doesn't use JSON itself, I'll do some prodding and see if I can find out.

> He closed your issue because you provided no command lin e output for him to look at. You didn't follow submission guidelines.

So as far as I was aware, I did.  I read the submission guidelines [here](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient), and followed it as best I could.

- I included a description of the request
- I suggested a method to research the issue

However I did fall flat on the last one, a proposed solution.  I assumed since it was not a bug report and they had already implemented it for Twitch, they would be in a better place to suggest a format structure etc. than I would be.

As it was not a bug report, I didn't include command line output, and as it was not a site support request, I didn't include an example URL.  (I guess I take these things too literally, the template I used was "Site Feature Request", which is distinct from their "Site Support Request").  I can see why they take these things seriously though, as they point out, they get a large number of "It doesn't work" issues filed.

**Comment by vxbinaca** [comment]
> I'd be surprised if YouTube doesn't use JSON itself, I'll do some prodding and see if I can find out.

It uses VTT as subtitles. I wish they' have used SRT but you work with what you get.

**Comment by Xalaxis** [comment]
I just had a look, and it seems to me like they use JSON for live chat replays.  If you look at one (e.g. https://www.youtube.com/watch?v=h4M5iFLKWqU) you should see the JSON chat data coming from https://www.youtube.com/live_chat_replay/get_live_chat_replay

**Comment by vxbinaca** [comment]
I'll look at it this weekend. Theres no ability for YTDL to get it though and we need that.

**Comment by brandongalbraith** [comment]
Relevant issue: https://github.com/taizan-hokuto/pytchat/issues/10

**Comment by vxbinaca** [comment]
I'm going back and opening select worthy issues since someone is working on a youtube-dl alternative, due to YTDL being stale and the devs not having time to work on it.

**Comment by Xalaxis** [comment]
Note there's been very good progress on this here: https://github.com/ytdl-org/youtube-dl/pull/26240

**Comment by vxbinaca** [comment]
Good luck getting staff to merge it. Try the youtube-dl**c** guys.

**Comment by siikamiika** [comment]
Just a guess, the youtube-dl maintainers might need more volunteers to review the pull requests. Looking at the commit log I see one person doing the releases and only a few others reviewing pull requests. Testing is important too, thanks for everyone who's been testing my PR.

https://ytdl-org.github.io/youtube-dl/ mentions \#youtube-dl at freenode. I didn't visit the channel, but maybe someone there could give some guidelines about reviewing.

Meanwhile I think it's fine to use patches or forks for projects that need new features (like this one), but I doubt hard forks are able to support all of these sites for very long https://ytdl-org.github.io/youtube-dl/supportedsites.html . Don't know what's the deal with youtube-dlc. If this https://github.com/blackjack4494/youtube-dlc/issues/37 ever happens, I hope it's upstreamed somehow.

**Comment by vxbinaca** [comment]
> Just a guess, the youtube-dl maintainers might need more volunteers to review the pull requests. Looking at the commit log I see one person doing the releases and only a few others reviewing pull requests. Testing is important too, thanks for everyone who's been testing my PR.
> 
> https://ytdl-org.github.io/youtube-dl/ mentions #youtube-dl at freenode. I didn't visit the channel, but maybe someone there could give some guidelines about reviewing.
> 
> Meanwhile I think it's fine to use patches or forks for projects that need new features (like this one), but I doubt hard forks are able to support all of these sites for very long https://ytdl-org.github.io/youtube-dl/supportedsites.html . Don't know what's the deal with youtube-dlc. If this [blackjack4494/youtube-dlc#37](https://github.com/blackjack4494/youtube-dlc/issues/37) ever happens, I hope it's upstreamed somehow.

Testing is important. One specific extractor for Twitch broke 3 or 4 months ago, a fixc was submitted *last year* for the impending API change that witch rolled out over many months. The fix sat all that time on their tracker, multiple people had tested it.

youtube-dl is dying. I don't like being exclusively hooked into them.

**Comment by siikamiika** [comment]
I haven't been following the development long enough to know about that, but I agree that it sounds pretty bad. Fixes to existing code should be highest priority.

What I'm concerned about is how many developers and users will find the fork if some effort that could be spent on improving the original project is spent elsewhere. If the current maintainers of youtube-dl actually are unwilling to give some power and responsibility to others, then I agree everyone should move on, but otherwise I'd try to negotiate handing over control of specific extractors to active contributors, for example.

Whatever the case, feel free to use what best suits the needs of the project.

**Comment by vxbinaca** [comment]
Can't really do that they blocked me so I'm going to help the new project

**Comment by vxbinaca** [comment]
We've switched the video downloader to ytdlc, when the author implements chat replay collection we'll implement the flag. He's started work on it.

**Comment by vxbinaca** [comment]
Switching to ytdlc has fixed this, they're pulled now as a subtitle in the youtube extractor and do not need our input.
