### ISSUE TITLE
Improve Test Harness

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#125]
Our tests leave much to be desired. This issue is a reminder to myself to ensure a higher level of code coverage and to confirm critical code paths have tests in place.

**Comment by vxbinaca** [comment]
To be honest, we all dropped the ball here I never thought a null keyvalue would utterly break tubeup. 

Testing your PR in a bit.

**Comment by vxbinaca** [comment]
Didn't switching to Github tests fix this?

**Comment by brandongalbraith** [comment]
Closing this for now. With the move to yt-dlp and improvements in our error handling of `.part` files (as well as some fixes IA has put in place to reject files we wouldn't want to upload), nothing glaring sticks out as a needed test. Open to suggestions of course, as well as breakage that presents itself in the future.
