### ISSUE TITLE
Skip Upload Mode

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#128]
Support specifying an argument on the command line (```--skip-upload```) that retrieves the digital artifacts from the target URL, but skips the upload to the Internet Archive. My thoughts on this use case are for local archiving in a local storage system, or preparing the items and artifacts for transfer to the Internet Archive in a way so that the item is not immediately publicly available (perhaps using a hard drive or USB flash drive).

**Comment by vxbinaca** [comment]
1. Internet Archive is hiding all (almost all) of our uploads based on client tags Jake pushed up to us a while back.
2. Local archiving can be done with youtube-dl, although I probably should print a command-line version of the library calls we do.

**Comment by brandongalbraith** [comment]
These are good points! This implementation would align with your second point, but instead of simply printing the command line options to use, it would run ytdl but skip the IA upload. Thoughts?

**Comment by vxbinaca** [comment]
why complicate the code? you'd have to write a corresponding feature to later upload it. 

Why when they could just upload it then and there? I don';[t see the scenario where the feature you propose would be useful. Example maybe?

**Comment by brandongalbraith** [comment]
@vxbinaca Good call, was able to write something to do this with only a dozen lines of Python.

**Comment by vxbinaca** [comment]
You could duplicate this feature you want by using just youtube-dl,. and teasing out how tubeup implements library calls then convert them to flags. Easy to do. Then you just move all the haul to `~/.tubeup/downloads` and push up each video based on ID )easy enough to enumerate, just list all the files, lip off the extensions then sort for uniqueness, boom you have your IDs, or just pre-enumerate using youtube-dl and `--get-id` on the channel)


But.....


If any of those videos were removed they won't **upload**. So we actually could use a opposite of your proposed feature. Skip downloads, or return that the video is alive no matter what, and upload the contents.
