### ISSUE TITLE
wayback machine question

### ISSUE THREAD

**Issue by ahmedtds** [bibanon/tubeup#131]
Hi, sorry if this is a too newbie question.

I want to know something, when we archive a youtube video with this tool to internet archive, does it also make it playable when someone checks that url from wayback machine?

**Comment by vxbinaca** [comment]
No, in the future please submit your questions on the Internet Archive to info@archive.org.

**Comment by ahmedtds** [comment]
this was a question about your tool, sorry for bothering but there was no need for this rudeness.

**Comment by vxbinaca** [comment]
> this was a question about your tool, sorry for bothering but there was no need for this rudeness.

No you're asking a Internet Archive question about their site. We are not them.

**Comment by ahmedtds** [comment]
no i asked something about this tool's abilities, reading comprehension much?

**Comment by vxbinaca** [comment]
> no i asked something about this tool's abilities, reading comprehension much?

The tool makes items on the main Archive.org site, not the wayback. I did comprehend what you said, you simply do not understand how Archive.org works. Ask the Internet Archive questions about their site.
