### ISSUE TITLE
abusive behaviour of one of your collaborators

### ISSUE THREAD

**Issue by ahmedtds** [bibanon/tubeup#132]
I asked this question: https://github.com/bibanon/tubeup/issues/131

One of your collaborators answered it very rudely for no reason when he could say same thing without being rude and also did it without comprehending what I asked.

I tried to clear my question and said there was no need for this rudeness.

He continued to insist on not comprehending my question and then issue is locked.

Closing the thread, saying just no, or saying _"tool makes items on the main Archive.org site, not the wayback"_ and closing, all fine. But I still fail to see why they had to act very rude like that.

My question was about this tool, not the archive.org site like claimed by person with comprehension problems continually.

I know how Archive.org works, my question was about if this tools makes any attempt to also make the youtube videos we uploaded available, viewable or indexed at wayback machine. Maybe I was gonna try to add such a functionality? I really fail to see a reason for this hostile behaviour.

I guess now you will ban me from repo but whatever. Some people feeds their soul by making other people sad it seems.

**Comment by vxbinaca** [comment]
Archive.org needs to link the items we upload to the Wayback. It's literally on them to do it.

**Comment by ahmedtds** [comment]
> It's literally on them to do it.
You're really an idiot, I let this go but now when I'm stumbled upon this again I realized how moron you were.
I literally tried to explain it to you like you were an 3 year old baby, you still couldn't comprehend it.
No idiot, it's not literally on them to do it.

You can use Archive.org's save page interface to save a page to their wayback machine right?
You can use their library to make these requests right?
There are scrapers out there which does exactly this right? Making "save page" requests to the archive org.
Got it this far? Probably not but let's continue.
Now my question was if this tool was also making such a "save page" request to the wayback machine when archiving videos, like some scrapers do, like alexa etc..
So it was a question about this tool, not the archive.org, it's not "literally on them to do it", it was all about this tool's capabilities and it was not a ridiculous fantasy question, it was a question about a pretty possible thing.

Now you can ban me but know that you are a fucking moron, fucking piece of shit.
