### ISSUE TITLE
Certain videos are impossible to upload

### ISSUE THREAD

**Issue by XXLuigiMario** [bibanon/tubeup#135]
While uploading a list of videos I've noticed some of them will pop up `warning: s3 is overloaded, sleeping for 30 seconds and retrying` and stall forever. However, this is not due to archive.org's S3 actually being overloaded. If you inspect the response from the server with Wireshark you might see the following:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SlowDown</Code><Message>Please reduce your request rate.</Message><Resource>Your upload of youtube-hEUfYL2OAnc from username ******@gmail.com appears to be spam. If you believe this is a mistake, contact info@archive.org and include this entire message in your email.</Resource><RequestId>9f1ddb74-2326-4e32-b64a-ab8a85f647b6</RequestId></Error>
```
Note "appears to be spam" as no matter how long you wait, days or even weeks, the server will reply with this error code for certain videos. Moreover, other videos can be uploaded without issue.
The only workaround for is to use the internetarchive CLI tool to upload a dummy file to force the creation of the identifier and then tell tubeup to upload said video.

To reproduce, try uploading this video: https://www.youtube.com/watch?v=hEUfYL2OAnc

**Comment by vxbinaca** [comment]
This is a internet archive issue. You've taken it to Jakes repo so I'll close this unless he sends you back here.
