### ISSUE TITLE
archive.org not handling newlines (\n) in descriptions

### ISSUE THREAD

**Issue by midgleyc** [bibanon/tubeup#140]
For example, looking at [this video](https://archive.org/details/youtube-uLALwPzJclw), by viewing the source of the description or the associated info.json, you can see that the description has newlines. These are dutifully uploaded to archive.org, but not visible on the page as presented.

Intended:
```
The Ask Project is made possible by donations from viewers like you. 
Please donate to the project at: 
* https://www.paypal.me/coreygilshuster 
* https://www.patreon.com/askproject
.
Want to know what Israelis and Palestinians in the Middle East really think about the conflict? Ask a question and I will get answers. 
```

Actual:
```
The Ask Project is made possible by donations from viewers like you. Please donate to the project at: * https://www.paypal.me/coreygilshuster * https://www.patreon.com/askproject . Want to know what Israelis and Palestinians in the Middle East really think about the conflict? Ask a question and I will get answers. 
```

----
The easiest solution to me would seem to be to replace '\n' with '\<br>' before uploading the description.
```
description_text = description_text.replace('\n', '<br>')
```

I can file a PR if you think this would work.

**Comment by vxbinaca** [comment]
So this is a item presentation issue with Archive.org. and won't edit the metadata .info.json, correct?

**Comment by midgleyc** [comment]
Correct.

**Comment by vxbinaca** [comment]
Submit a PR and I'll test/merge, then push a new version
