### ISSUE TITLE
Remove IP addresses from info.json files

### ISSUE THREAD

**Issue by imabritishcow** [bibanon/tubeup#145]
IP addresses are in the URLs for the formats array.
![image](https://user-images.githubusercontent.com/49381066/102845247-22762900-43db-11eb-9932-7a4b08705b1d.png)

This could be an issue for people uploading using their home internet. It could be fixed by using regex on the file outputted by youtube-dl before uploading.

**Comment by vxbinaca** [comment]
We know. You could submit a PR to fix it.
