### ISSUE TITLE
ModuleNotFoundError: No module named 'youtube_dl.downloader'

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#149]
```
$ tubeup "https://www.youtube.com/watch?v=OS0QNJ0Xbaw"
Traceback (most recent call last):
  File "/home/user/.local/bin/tubeup", line 5, in <module>
    from tubeup.__main__ import main
  File "/home/user/.local/lib/python3.8/site-packages/tubeup/__main__.py", line 59, in <module>
    from tubeup.TubeUp import TubeUp
  File "/home/user/.local/lib/python3.8/site-packages/tubeup/TubeUp.py", line 12, in <module>
    from youtube_dl import YoutubeDL
  File "/home/user/.local/lib/python3.8/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/home/user/.local/lib/python3.8/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
ModuleNotFoundError: No module named 'youtube_dl.downloader'
```
Everything is installed correctly/up-to-date, and youtube-dl works on its own.

**Comment by vxbinaca** [comment]
Works for me when I ran that exact command

```tubeup "https://www.youtube.com/watch?v=OS0QNJ0Xbaw"```

`[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.9.1 (CPython) - Linux-5.9.16-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
video doesn't have subtitles
[debug] Default format spec: bestvideo+bestaudio/best
There are no annotations to write.
[download]  67.6% of 43.59MiB at 28.40MiB/s ETA 00:00`

**Comment by mariomadproductions** [comment]
Is there some way I can provide extra info to help with debugging this?

**Comment by vxbinaca** [comment]
I just grabbed the latest YTDL, still works for me. 

'pip3 install --user -U tubeup youtube-dl jsonpointer jsonpatch docopt six total-ordering tqdm certifi idna chardet urllib3 requests contextlib2 schema backports.csv internetarchive tubeup pip '

**Comment by mariomadproductions** [comment]
No luck after running that on my end.

**Comment by vxbinaca** [comment]
Okay tell me the details of the platform you have that installed on. Is it a linux machine or WLS2?

**Comment by mariomadproductions** [comment]
Linux Mint 20.1  I've made sure stuff is up-to-date (`sudo apt-get update -y && sudo apt-get dist-upgrade -y`). Not using a python virtualenv.

**Comment by vxbinaca** [comment]
You're using it on bare metal and not in WLS2? Your instalation method for youtube-dl was through pip?

**Comment by mariomadproductions** [comment]
Sorry yeah, bare metal. Yep, through pip.

**Comment by mariomadproductions** [comment]
Hmm. By removing the youtube-dl binary from /usr/local/bin, doing `sudo pip3 uninstall youtube-dl` and then `sudo pip3 install youtube-dl`, I now get the same error from just running youtube-dl from the terminal.
```
$ youtube-dl
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 5, in <module>
    from youtube_dl import main
  File "/home/user/.local/lib/python3.8/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/home/user/.local/lib/python3.8/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
ModuleNotFoundError: No module named 'youtube_dl.downloader'
```

**Comment by mariomadproductions** [comment]
I don't know what's caused this problem, but creating a python virtualenv appears to be a reasonable workaround.
