### ISSUE TITLE
Convert VTT closed caption files to SRT

### ISSUE THREAD

**Issue by jjjake** [bibanon/tubeup#15]
I think we might be able to do this as part of an archive.org derive process, so they would be converted on archive.org servers after upload automatically. I will look into this.

**Comment by vxbinaca** [comment]
Thank you, that would be great before we really start doing large rips.

**Comment by jjjake** [comment]
It sounds like we would like to update our video player to support WebVTT files in the near future, or at the very least derive .vtt files to .srt.

I would recommend moving forward, not worrying about converting the vtt files to srt's. We'll either be able to support vtt files in our video player soon, or be able to convert them on our end (we could re-derive your already uploaded items, after we role out the updates).

No promises on when this will happen, but it's on the roadmap!

**Comment by vxbinaca** [comment]
Well right now I'm manually doing VTTs but this is good to know, my targets aren't subtitle videos right now for the most part.
