### ISSUE TITLE
Consider moving to yt-dlp

### ISSUE THREAD

**Issue by TheFrenchGhosty** [bibanon/tubeup#152]
https://github.com/bibanon/tubeup/commit/e7310386ea3751857e6a10ae3af408e0affba595#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

youtube-dlc is indeed abandoned, however it was forked: https://github.com/pukkandan/yt-dlp

Related: https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/issues/37

**Comment by vxbinaca** [comment]
we use youtube-dl right now because it's in active development
