### ISSUE TITLE
Uploaded facebook videos use the wrong metadata (title, description, etc.)

### ISSUE THREAD

**Issue by exurd** [bibanon/tubeup#157]
Videos uploaded from Facebook via tubeup takes the wrong metadata; the description is now the title and the title is now the author name/uploader. Right now, you have to manually fix them by hand.

Here is a screenshot of what it was like:
![facebook-206914099986628](https://user-images.githubusercontent.com/7785022/112033406-490c4300-8b35-11eb-90c2-a2797f5770ef.png)
Here's [the original](https://www.facebook.com/FezMaker/videos/206914099986628/) and [the archived video](https://archive.org/details/facebook-206914099986628).

**Comment by vxbinaca** [comment]
leave a issue with YTDL on the FB extractor - we can't hardcode fixes for everyone's persnickity issues.

**Comment by vxbinaca** [comment]
also get the URL from the source post not the account who shared it. Take the extra few seconds to click on the original post and get that URL.
