### ISSUE TITLE
tubeup error 

### ISSUE THREAD

**Issue by Zopolis4** [bibanon/tubeup#158]
After trying to download a channel multiple times, I continued to get this error message, and tubeup said I should report it.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tubeup/__main__.py", line 94, in main
    for identifier, meta in tu.archive_urls(URLs, metadata, proxy_url,
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 371, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 285, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/---/.tubeup/downloads/UCR-rdMVYBrfdk7LbLfLkRpQ.info.json'
```

**Comment by brandongalbraith** [comment]
@Zopolis4 please provide the link you used as an argument for TubeUp for troubleshooting.￼

**Comment by Zopolis4** [comment]
https://www.youtube.com/channel/UCR-rdMVYBrfdk7LbLfLkRpQ, although i get the same issue on https://www.youtube.com/c/KlericsVeryCoolURL/

**Comment by brandongalbraith** [comment]
@Zopolis4 Channel uploads are intermittently broken at the moment (See https://github.com/bibanon/tubeup/issues/61 for details). An interim fix is to [dump the channel's list of videos to a file](https://archive.zhimingwang.org/blog/2014-11-05-list-youtube-playlist-with-youtube-dl.html), and then loop over the file.

**Comment by Zopolis4** [comment]
Sorry, I am very new to Linux (installed it to use tubeup), so could you post the commands required to dump the videos and loop over it?

**Comment by brandongalbraith** [comment]
[This Reddit thread](https://www.reddit.com/r/DataHoarder/comments/9ozzzu/youtubedl_for_entire_channel/) should help you download all videos from the Youtube channel you're attempting to grab. 

It is important to note that only videos that are of a transient, impermanent, or "at risk" nature should be archived to the Internet Archive using tubeup.

**Comment by vxbinaca** [comment]
@brandongalbraith apart of the issue template should be forcing people to display full terminal output, including version numbers of the software they're using and the environment they're using. He could have installed youtube-dl from the stale repository that the rest of a distros software comes with.

**Comment by brandongalbraith** [comment]
Yes! Excellent point, I will include this in the template tomorrow when I
work on it.
