### ISSUE TITLE
Add Bug Report Template For Issues

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#160]
@vxbinaca I don't have the necessary repo access to do this.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Sample template below:

## Checklist

- [ ] I'm reporting a broken support issue
- [ ] I've verified that I'm running the latest version of tubeup
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the issues for similar bug reports including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by vxbinaca** [comment]
@antonizoon Give him whatever access he needs, please and thank you.

**Comment by vxbinaca** [comment]
I set you to maintainer. If you need more access talk to @antonizoon

**Comment by brandongalbraith** [comment]
Thank you @vxbinaca!

**Comment by brandongalbraith** [comment]
Hey @antonizoon, not sure if it's an access issue or not, but I still don't have the ability to setup an issue template when in the Settings panel (see below as that's all I have access to). I don't want to be overprivileged, just enough access to get an issue template setup to streamline managing support requests that come in. Let me know how we can get this tackled when you've got time. Thanks!

![Screen Shot 2021-04-26 at 5 19 02 PM](https://user-images.githubusercontent.com/350893/116158014-8ffcd380-a6b3-11eb-95e7-d106ba6f4447.png)
![Screen Shot 2021-04-26 at 5 19 11 PM](https://user-images.githubusercontent.com/350893/116158025-94c18780-a6b3-11eb-965c-c675c4818ea5.png)
![Screen Shot 2021-04-26 at 5 19 15 PM](https://user-images.githubusercontent.com/350893/116158034-968b4b00-a6b3-11eb-887b-ff5273acfbef.png)

**Comment by vxbinaca** [comment]
I promoted you to Admin. I don't think theres a higher level I can move you to.

**Comment by brandongalbraith** [comment]
@vxbinaca Thanks! As soon as I'm done setting up the template, I'll let you know and you can downgrade my access 👍

**Comment by vxbinaca** [comment]
> @vxbinaca Thanks! As soon as I'm done setting up the template, I'll let you know and you can downgrade my access 👍

I see no reason to lower your privledges.
