### ISSUE TITLE
Any way to collect timestamps and comments?

### ISSUE THREAD

**Issue by MisterSheeple** [bibanon/tubeup#164]
I'm noticing that whenever you try to put the timestamp into something, it comes out as "NA". This happens in youtube-dl and every fork of it I can find. Is there any workaround that allows for the retrieval of timestamps?

Additionally, is there any way to save comments within a tubeup upload?

**Comment by brandongalbraith** [comment]
@MisterSheeple can you provide a timestamp example in this thread? Also, supporting ripping comments and uploading them alongside other digital artifacts is on my TODO list.

**Comment by MisterSheeple** [comment]
> @MisterSheeple can you provide a timestamp example in this thread? Also, supporting ripping comments and uploading them alongside other digital artifacts is on my TODO list.

I'm sorry but it's not giving me a timestamp at all so I don't really have an example to give you.

**Comment by brandongalbraith** [comment]
Do you mean you're providing the timestamp of the video in the video link you're providing to tubeup on the command line? Or is this timestamp metadata somewhere?

**Comment by vxbinaca** [comment]
What do you mean by timestamp? Do you mean the sections in video that are made by the creator to break it up into parts they name?

Because that's a youtube-dl thing. They need to allow for it in the extractor

**Comment by MisterSheeple** [comment]
> Do you mean you're providing the timestamp of the video in the video link you're providing to tubeup on the command line? Or is this timestamp metadata somewhere?

Oh no, I mean a Unix timestamp of when the video was uploaded.

**Comment by MisterSheeple** [comment]
> What do you mean by timestamp? Do you mean the sections in video that are made by the creator to break it up into parts they name?
> 
> Because that's a youtube-dl thing. They need to allow for it in the extractor

No, I'm referring to the upload date in the form of Unix time, sorry for the confusion.

**Comment by vxbinaca** [comment]
The upload time is in the metadata and is transferred to the item. If it's not in unix time you can convert it. We work with that youtube, and youtube-dls extractor give us. Ask them to implement this. Furthermore, we have to then take that time and make it conform with a RFC standard Internet Archive uses.

**Comment by MisterSheeple** [comment]
> The upload time is in the metadata and is transferred to the item. If it's not in unix time you can convert it. We work with what youtube, and youtube-dls extractor give us. Ask them to implement this. Furthermore, we have to then take that time and make it conform with a RFC standard Internet Archive uses.

Well that's the upload date, not the exact time. What I'm looking for is the exact date and time the video was uploaded. I've been told that's something that YouTube provides.

**Comment by brandongalbraith** [comment]
@MisterSheeple Provide an example youtube url and I'll investigate.

**Comment by MisterSheeple** [comment]
> @MisterSheeple Provide an example youtube url and I'll investigate.

https://www.youtube.com/watch?v=ySRgVo1X_18

**Comment by vxbinaca** [comment]
> > @MisterSheeple Provide an example youtube url and I'll investigate.
> 
> https://www.youtube.com/watch?v=ySRgVo1X_18

So Brandom means show us a video where the metadata or data given by the site provides for a Unix timestamp. 1) I don't think it be like that and 2) We need to conform to RFC for time output so it jives with Archive,org.

I'll wait for that Unix time being in the site data tho.

**Comment by brandongalbraith** [comment]
Standby y'all, let's see what I can get, will put details here.

**Comment by MisterSheeple** [comment]
In particular I'm looking at youtube-dl's %(timestamp)s output function. That's there but it produces "NA" when used. Seems either like a bug or something that YouTube got rid of on their end.

**Comment by vxbinaca** [comment]
Okay so then it's youtube-dl's issue or youtubes. either way we can't supply this thing you want.

**Comment by brandongalbraith** [comment]
Navigating to https://www.youtube.com/watch?v=ySRgVo1X_18 in a browser window I get November 8, 2013 as the upload date:

![image](https://user-images.githubusercontent.com/350893/124523222-d5c4cf00-ddbb-11eb-8c48-a9b8907f4175.png)

When I run `youtube-dl --write-info-json https://www.youtube.com/watch\?v\=ySRgVo1X_18` (which replicates what tubeup has youtube-dl perform to retrieve the video's digital artifacts), the following files are written to disk:

```
Minecraft - The Story of Mojang (Official Version!)-ySRgVo1X_18.info.json
Minecraft - The Story of Mojang (Official Version!)-ySRgVo1X_18.mp4
```

The contents of `Minecraft - The Story of Mojang (Official Version!)-ySRgVo1X_18.info.json` are at https://gist.github.com/brandongalbraith/a1a1e91a32c24739c568baf04a6949dd.

I don't see a `timestamp` key, _but there is an `upload_date` key [available](https://gist.github.com/brandongalbraith/a1a1e91a32c24739c568baf04a6949dd#file-minecraft-the-story-of-mojang-official-version-ysrgvo1x_18-json-L440):

`"upload_date":"20131108",`

 and that is what is used to set the `Publication date` for an Internet Archive item.

Based on this research, I don't believe we can provide a timestamp (and the corresponding resolution that comes with it) for items, only upload/publication dates (which are YYYY-MM-DD format and datetime coarse).

**Comment by MisterSheeple** [comment]
Alright thanks for the help!

**Comment by brandongalbraith** [comment]
I rescind my previous statement! It looks like more granular time and data information is available! When I input the Youtube URL @MisterSheeple provided into the Youtube DataViewer by Amnesty International (https://citizenevidence.amnestyusa.org/), the following data is returned:

```
Video ID: ySRgVo1X_18
Upload Date (YYYY/MM/DD): 2013-11-08
Upload Time (UTC): 21:55:19 (convert to local time)
```

This leads me to believe this UTC date/time data _could_ be converted into a unix timestamp. @MisterSheeple Is a unix timestamp absolutely necessary? Or would this additional UTC hour-minute-second resolution be sufficient for your needs?

**Comment by MisterSheeple** [comment]
> I rescind my previous statement! It looks like more granular time and data information is available! When I input the Youtube URL @MisterSheeple provided into the Youtube DataViewer by Amnesty International (https://citizenevidence.amnestyusa.org/), the following data is returned:
> 
> ```
> Video ID: ySRgVo1X_18
> Upload Date (YYYY/MM/DD): 2013-11-08
> Upload Time (UTC): 21:55:19 (convert to local time)
> ```
> 
> This leads me to believe this UTC date/time data _could_ be converted into a unix timestamp. @MisterSheeple Is a unix timestamp absolutely necessary? Or would this additional UTC hour-minute-second resolution be sufficient for your needs?

No no, unix isn't necessary. As long as it provides an exact time, it suits my needs.

**Comment by vxbinaca** [comment]
Wonder where they're getting the time of day like that.

**Comment by brandongalbraith** [comment]
@MisterSheeple After doing additional research, this is something that is dependent on youtube-dl supporting and tubeup is unable to support at this time. I experimented while relying on youtube-dl's documentation and your youtube url you provided, and also cannot get the `timestamp` placeholder to work with youtube URLs. [A similar issue in the ytdl repo did not get a helpful response.](https://github.com/ytdl-org/youtube-dl/issues/25078)

Until youtube-dl extends support for adding the `timestamp` key into the JSON metadata written to disk, I suggest using https://citizenevidence.amnestyusa.org/ (in a web browser) or https://www.googleapis.com/youtube/v3/videos?id=<VIDEO_ID>&part=snippet,statistics,recordingDetails&key=<API_KEY> (API call) (which will return `publishedAt": "2013-11-08T21:55:19Z"` in the response body of the API call) to get the exact date and time of video publication.

I apologize we couldn't be more helpful with this issue.

**Comment by MisterSheeple** [comment]
> @MisterSheeple After doing additional research, this is something that is dependent on youtube-dl supporting and tubeup is unable to support at this time. I experimented while relying on youtube-dl's documentation and your youtube url you provided, and also cannot get the `timestamp` placeholder to work with youtube URLs. [A similar issue in the ytdl repo did not get a helpful response.](https://github.com/ytdl-org/youtube-dl/issues/25078)
> 
> Until youtube-dl extends support for adding the `timestamp` key into the JSON metadata written to disk (and reliably retrieves and provides that piece of data instead of `NA`), I suggest using https://citizenevidence.amnestyusa.org/ (in a web browser) or https://www.googleapis.com/youtube/v3/videos?id=<VIDEO_ID>&part=snippet,statistics,recordingDetails&key=<API_KEY> (API call) (which will return `publishedAt": "2013-11-08T21:55:19Z"` in the response body of the API call) to get the exact date and time of video publication.
> 
> I apologize we couldn't be more helpful with this issue.

It's okay, your help is greatly appreciated!
