### ISSUE TITLE
When I type in tubeup and then the url it gives me an error message that no matches were found for (and then the url inputted)

### ISSUE THREAD

**Issue by gtaillefer** [bibanon/tubeup#165]
Hello everyone, 
So as the title suggests whenever I type in "tubeup" and then the url of the YouTube video that I want to mirror to the Wayback Machine, it gives me this error message:
`_name-of-user_@MacBook-Air ~ % tubeup https://www.youtube.com/watch?v=dzw3NPyLReI`
`zsh: no matches found: https://www.youtube.com/watch?v=dzw3NPyLReI`
If it helps I am using a new 2020 MacBook with the M1 chip on Big Sur. 
If anyone could help that would be great
thanks

**Comment by vxbinaca** [comment]
`python3 -m tubeup https://www.youtube.com/watch?v=dzw3NPyLReI`

It's likely a problem with your python environment.

**Comment by gtaillefer** [comment]
thank you for the response! What would you suggest I should do to fix the supposed my python environment? I also think that there is the possibility that this might be due to the fact that apple has switched over from bash to zsh.

**Comment by vxbinaca** [comment]
dunno what commands you ran

**Comment by gtaillefer** [comment]
I followed this guide [https://jenwalker.home.blog/2020/03/14/how-to-automate-mirroring-youtube-videos-to-archive-org-with-tubeup/] 
Because the first command that you put on the front page wouldn't work if I had replaced the apt-get and apt with "port" (I am using MacPorts for this), and then I also replaced each point in each command (in the link) where it said "3.7" (the python version) with 3.8 or 3.9. But then afterwards I followed the rest of the commands that you said to use along with the set of commands in the link.

**Comment by vxbinaca** [comment]
most of us aren't bourgeois enough to own Apple hardware. looks like you need to set your new path in your ZSH config. 

consider using OhMyZSH as well thats just a personal thing of mine

**Comment by gtaillefer** [comment]
Okay well I am very thankful for your time in trying to help me. I think ill look more into OhMyZSH and will do more digging. Thank you and have a good rest of your day!

**Comment by brandongalbraith** [comment]
@gtaillefer I currently run tubeup on an Intel MacBook Air, so I have yet to run through the install process on M1 Silicon to see what breaks and needs fixing. When time permits, I will test installing on my M1 MacBook Air and update our installation instructions. Sorry for the troubles you're having! A Dockerfile is also in the plans, but that's likely not helpful if you're not using containers as runners.

**Comment by gtaillefer** [comment]
Its alright! shifting from one processor to the next won't exactly help much for developers so it makes sense why a lot of people are having trouble with some things on the new mac. I wish you luck and thank you!
