### ISSUE TITLE
Suggestion: add option to download and upload separately

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#166]
If you want to archive a lot of videos, I think it'd be useful if you could download them in one session, then upload them in another. This way the downloading of at-risk videos won't be delayed by Internet Archive slowdown/slow upload speeds.

**Comment by brandongalbraith** [comment]
I'm a fan. Backlogged.

**Comment by vxbinaca** [comment]
Trouble you'll run into is if they're gone from the host they'll just sit on your disk and not upload

**Comment by mariomadproductions** [comment]
Another use for this could be just to maintain a local archive, or a cloud archive that doesn't rely on archive.org, but still make use of the automation that tubeup provides.

**Comment by brandongalbraith** [comment]
@mariomadproductions I was thinking along these lines that if we're going to skip the Internet Archive upload, an additional option would be to compress the bundle of digital artifacts into a single file for streamlined storage and management. Thoughts?

**Comment by mariomadproductions** [comment]
I think as storage/archive formats do differ quite a lot between use-cases, so its probably best to leave that to the user to do themselves via shell scripting. But maybe tubeup could provide an option (like "run this command/script after each video is downloaded" or something) to allow easier integration with shells scripting - not sure.

**Comment by mariomadproductions** [comment]
> Trouble you'll run into is if they're gone from the host they'll just sit on your disk and not upload.
> 
> You rip channels at your own risk .

I don't really follow. You mean tubeup checks if the video is online before an upload can start?

**Comment by vxbinaca** [comment]
> @mariomadproductions I was thinking along these lines that if we're going to skip the Internet Archive upload, an additional option would be to compress the bundle of digital artifacts into a single file for streamlined storage and management. Thoughts?

Youtube-dl + 7zip could do this outside of tubeup?

Tubeup is a mirroring application. Youtube-dl downloads, internetarchive uploads. It is a middleman to make it easy to mirror.

I'm really failing to see the benefit here and sense scope creep of this ask.

> Another use for this could be just to maintain a local archive

Youtube-dl does this well on it's own. You'd do well to familiarize yourself with it's flags.

**Comment by Delta-473** [comment]
It's been a while since I used Tubeup but can an extension on this be an option that it will upload the video after it has downloaded it. Because I have a vps that has a better connection then my home network but not the storage space to store an entire channel before it get's uploaded.

**Comment by mariomadproductions** [comment]
In the meantime, I guess you can use `youtube-dl --restrict-filenames --verbose --newline --continue --retries 9001 --fragment-retries 9001 --dump-json --write-info-json --write-description --write-thumbnail --write-annotations --write-sub --all-subs --ignore-errors --fixup warn --no-overwrites --console-title --prefer-ffmpeg --no-call-home`, which should reflect the flags tubeup currently uses. But this command would have to remade if tubeup changes the flags.

**Comment by vxbinaca** [comment]
> It's been a while since I used Tubeup but can an extension on this be an option that it will upload the video after it has downloaded it. Because I have a vps that has a better connection then my home network but not the storage space to store an entire channel before it get's uploaded.

Consider getting a new VPS with more storage.

> In the meantime, I guess you can use `youtube-dl --restrict-filenames --verbose --newline --continue --retries 9001 --fragment-retries 9001 --dump-json --write-info-json --write-description --write-thumbnail --write-annotations --write-sub --all-subs --ignore-errors --fixup warn --no-overwrites --console-title --prefer-ffmpeg --no-call-home`, which should reflect the flags tubeup currently uses. But this command would have to remade if tubeup changes the flags.

You technically don't need the retries that high we have that set as a safety to absolutely as much as possible prevent a download from timing out.

**Comment by brandongalbraith** [comment]
@mariomadproductions Did the command line arguments [you provided here](https://github.com/bibanon/tubeup/issues/166#issuecomment-881937869) work for you? When I run that command line with a Youtube link as the parameter, the only result is JSON (no other artifacts are downloaded).

**Comment by mariomadproductions** [comment]
> @mariomadproductions Did the command line arguments [you provided here](https://github.com/bibanon/tubeup/issues/166#issuecomment-881937869) work for you? When I run that command line with a Youtube link as the parameter, the only result is JSON on the console (no artifacts are downloaded or written to disk).

Ah yeah, I had to change it a bit to remove some "simulate" commands, but I forgot to edit my post. Here's the updated command:
`youtube-dl --restrict-filenames --verbose --newline --continue --retries 9001 --fragment-retries 9001 --write-info-json --write-description --write-thumbnail --write-annotations --write-sub --all-subs --ignore-errors --fixup warn --no-overwrites --console-title --prefer-ffmpeg --no-call-home`

**Comment by vxbinaca** [comment]
Why does someone need to download a video file, hold onto it, and then upload it later?

I see a few problems with that scenario. People messing with metadata. Peoples bargain Seagate hard drives developing errors and data being corrupted. If something need to go onto Archive.org then it's a immediate right now thing.

I'm really failing to see the use of this feature request when one could just use youtube-dl. Why does Tubeup now need to have a option to download only?

**Comment by brandongalbraith** [comment]
Good question Paul. I’m currently archiving a bunch of channels covering
human rights abuses in a country I won’t mention here. The Internet Archive
isn’t currently accepting them for upload, but a related party will and get
them to the right people if I provide the data via usb stick or hard drive.
Therefore, I’m essentially queuing them for ingest to prevent a loss of
data in the event Youtube takes the videos down before they Internet
Archive ingests them.

**Comment by vxbinaca** [comment]
Cool lets update the README with a `youtube-dl` command that replicates the download functionality then.

**Comment by mariomadproductions** [comment]
> Why does someone need to download a video file, hold onto it, and then upload it later?
> 
> I see a few problems with that scenario. People messing with metadata. Peoples bargain Seagate hard drives developing errors and data being corrupted. If something need to go onto Archive.org then it's a immediate right now thing. Inevitably they'll download-only something. but go to upload it and one of us got to it first.
> 
> I'm really failing to see the use of this feature request when one could just use youtube-dl. Why does Tubeup now need to have a option to download only?

A. The internet archives policy on youtube mirrors is unclear
B. In my experience, I can only upload a handful of videos at a time, before the IA servers seem to time out for the rest of the day.

**Comment by vxbinaca** [comment]
That's their thing not ours, use the command you placed in here to download videos.

**Comment by brandongalbraith** [comment]
Hey y'all, circling back on this. I understand the need for this functionality, I just don't have the time to build at. If someone wants to submit a PR that provides a tubeup option to create a tarball of artifacts after a retrieval, along with a command to read that tarball and call the appropriate options in https://github.com/jjjake/internetarchive to upload the contents as would occur during an archival operation, I'm happy to review and help get it merged to `master`.

**Comment by vxbinaca** [comment]
Scope creep. He need to read ytdlps readme on how to download.

They have a unclear policy on YouTube rips? Oh well. To the dice with them.

This functionality is a time sink for other issues that could be fixed and code that would have to be maintained.

Mario, if you need to archive something do it when you feel it needs to be saved not this lagged archival stuff. Ask me how I know this, losing channels because I didn't run a command.

If IA doesn't like it it's not in my control.

**Comment by upintheairsheep** [comment]
> In the meantime, I guess you can use `youtube-dl --restrict-filenames --verbose --newline --continue --retries 9001 --fragment-retries 9001 --dump-json --write-info-json --write-description --write-thumbnail --write-annotations --write-sub --all-subs --ignore-errors --fixup warn --no-overwrites --console-title --prefer-ffmpeg --no-call-home`, which should reflect the flags tubeup currently uses. But this command would have to remade if tubeup changes the flags.
> 
> edit: fixed command - `youtube-dl --restrict-filenames --verbose --newline --continue --retries 9001 --fragment-retries 9001 --write-info-json --write-description --write-thumbnail --write-annotations --write-sub --all-subs --ignore-errors --fixup warn --no-overwrites --console-title --prefer-ffmpeg --no-call-home`

Now for YT-DLP change the first word to YT dlp and also put —write-comments to get comments
