### ISSUE TITLE
Archiving a channel fails with a FileNotFound Error

### ISSUE THREAD

**Issue by Shumatsu** [bibanon/tubeup#168]
When trying to archive a channel, tubeup fails with an error stating it's unable to find a playlist .json file. There's indeed no playlist json file in the download directory.
Channel in question: https://www.youtube.com/channel/UC_-vS9T3_X52HWMhIBsHouw

```python
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tubeup/__main__.py", line 96, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 381, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 293, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/arkivist/.tubeup/downloads/PLMhJPMw9Rnf_foh-qrDwnplf3wBIr9ZiV.info.json'
```

**Comment by brandongalbraith** [comment]
Known issue, we're working on it, my apologies for the inconvenience.

**Comment by vxbinaca** [comment]
Try adding `/videos` to the end of the URL, re-rip, the files should still be on your disk

**Comment by issuecommitor** [comment]
Got the same .json FIleNotFoundError, is there something in a log i could provide?

**Comment by vxbinaca** [comment]
Try this again please we just switched downloaders.

**Comment by Shumatsu** [comment]
Just ran it with a 10-vid channel. Went all good, and new downloader also saves comments from premiere I noticed.

**Comment by brandongalbraith** [comment]
Awesome to hear @Shumatsu, thanks for the report. Closing this issue, can be reopened if the issue occurs again. cc @vxbinaca 

New extractor grabs both live chat (subtitles file) and comments (infojson), so that's cool 🚀 .

**Comment by vxbinaca** [comment]
Boy switching out the downloader sure works wonders

**Comment by brandongalbraith** [comment]
I only regret we didn't do it sooner! 😬
