### ISSUE TITLE
Implement os.path.expanduser for filesystem access 

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#17]
See title.

Every time I have tried setting it to ```~/``` or ```$HOME``` it's failed. I would have assume with ```$HOME``` we were dealing with a env problem with bash but ```~/``` doesn't work either.

The result currently is, it can't write to the archive file on the youtube-dl end of the script, so progress made through a channel or individual items isn't recorded for subsequent runs on a channel.

**Comment by vxbinaca** [comment]
```import os.path```
```from os.path import expanduser```

From there I'm stuck. I don't know how to set the variable on the archive file to point to ~/.tubeup

**Comment by jjjake** [comment]
@vxbinaca I'm not sure where you're trying to add this, let me know and I can submit a PR.

Here's how `os.path.expanduser()` works, though:

```
>>> import os.path
>>> os.path.expanduser('~/.tubeup')
'/home/jake/.tubeup'
```

Does that make sense?

**Comment by vxbinaca** [comment]
@jjjake yes it makes sense, what I'm trying to do is resolve this:

```ERROR: [Errno 2] No such file or directory: '~/.tubeup/.ytdlarchive'````

it's not creating the file on a fresh install and I'll retest it, but it's not updating the file either if I recall correctly.
