### ISSUE TITLE
Add flag `--write-comments`

### ISSUE THREAD

**Issue by TheTechRobo** [bibanon/tubeup#180]
```
--write-comments                 Retrieve video comments to be placed in the
                                 infojson. The comments are fetched even
                                 without this option if the extraction is
                                 known to be quick (Alias: --get-comments)
```

YOutube comments are important; they show the culture of a video; it would be really nice if they are gotten. I haven't noticed the comments in info.json file.

**Comment by vxbinaca** [comment]
If this causes any problems with video retrieval we're not getting comments will test this later

**Comment by brandongalbraith** [comment]
@pukkandan Should we be getting Youtube comments written to the JSON blob if `writeinfojson: True`? Or is it expected we'd also have to set `getcomments: True`?

https://github.com/bibanon/tubeup/blob/master/tubeup/TubeUp.py#L239

**Comment by brandongalbraith** [comment]
@pukkandan Should we be getting Youtube comments written to the JSON blob if `writeinfojson: True`? Or is it expected we'd also have to set `getcomments: True`?

https://github.com/bibanon/tubeup/blob/47cb6b7fe9741182900b7de6b257ad843b4a9130/tubeup/TubeUp.py#L239

https://github.com/yt-dlp/yt-dlp/blob/e6f21b3d925ea708955c60c400a31fc2e0e36ac0/yt_dlp/__init__.py#L351-L354

**Comment by pukkandan** [comment]
> Should we be getting Youtube comments written to the JSON blob if writeinfojson: True? Or is it expected we'd also have to set getcomments: True

Fetching comments is a very slow process. Hence why it is disabled by default. You have to explicitly enable `getcomments: True` to fetch the comments

> If JSON is not printed anywhere, but comments are requested, save it to file

This is making sure that when a user runs `yt-dlp --write-comments URL`, the the comments are not just feteched and discarded, but actually written to disk. Since you guys are using the API and not the CLI, this is not really applicable for you

**Comment by vxbinaca** [comment]
Yeah thats what I thought, it'd be slow. Also comments retrieval would lead to more triggering of hosts spam or anti-rip protections.

Make this a flag but don't enable it by default. I'm not outright opposed but enabling it by default will cause issues.

**Comment by brandongalbraith** [comment]
Thank you for the context @pukkandan, agreed @vxbinaca this should be an option but definitely not a default.

**Comment by TheTechRobo** [comment]
Sounds great - didn't think of the speed issue!

**Comment by vxbinaca** [comment]
Another thing you're not thinking about is if there's a site change in comments that breaks ripping. You'd lose the whole video because of something that's frankly optional and not really apart of the video it's self.

But yeah make it a flag and we'll merge.

**Comment by upintheairsheep** [comment]
Also save this info: replies, likes of the comment, hearts, pins, time, name, also save profile pictures if possible

**Comment by upintheairsheep** [comment]
> Another thing you're not thinking about is if there's a site change in comments that breaks ripping. You'd lose the whole video because of something that's frankly optional and not really apart of the video it's self.
> 
> But yeah make it a flag and we'll merge.

Comments archive after the video. They should be stored separately in a folder called /Comments/

**Comment by TheTechRobo** [comment]
...?

I don't think you understand how the yt-dlp write-comments flag works.

- Everything except the PFP + channel of the comment is saved. Doing otherwise would require a parser for the JSON it writes
- `Comments archive after the video. They should be stored separately in a folder called /Comments/` - that's not how it works. yt-dlp saves the stuff in the info.json metadata file and indeed downloads comments **BEFORE** the video download, like others have said

and yeah, I need to get onto this. Been having trouble finding motivation tho, I need to sit down and figure out the relevant bits of the codebase

**Comment by TheTechRobo** [comment]
Ooh, didn't see that PR. I don't think I got a notif.

I'll try it in a bit and see if it works :D

**Comment by vxbinaca** [comment]
> Re @vxbinaca: I don't think comments being broken would mess up the video download, it'll just fail downloading comments (you can even Ctrl+C the comment downloading in the middle of it to skip) but feel free to correct me if I'm wrong

Ctrl-C while in Tubeup kills Tubeup since Tubeup is making the library calls.

**Comment by TheTechRobo** [comment]
Right, I know, I'm talking about vanilla dlp.

**Comment by vxbinaca** [comment]
Make it a flag not on by default and I'll look at it.

**Comment by TheTechRobo** [comment]
That's what I was planning on doing :thumbsup:

**Comment by johtso** [comment]
@TheTechRobo any luck? this would be a great addition to have..

**Comment by TheTechRobo** [comment]
No, I've been busy lately.

**Comment by brandongalbraith** [comment]
We would absolutely be supportive of someone submitting a PR with this functionality. Please consider this an informal "request for contributors."

**Comment by TheTechRobo** [comment]
I definitely want to do this; just having trouble finding motivation, as I don't use tubeup anymore...

**Comment by brandongalbraith** [comment]
@TheTechRobo Definitely don't feel like my comment implied an obligation. I myself have a hard time finding any time to put the enhancements and refactors into tubeup I'd love to do. If you have time, great! If not, no worries at all!

**Comment by johtso** [comment]
I'll take a look ✨
