### ISSUE TITLE
Bug report: 

### ISSUE THREAD

**Issue by Jenni32222** [bibanon/tubeup#182]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [X] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the issues (closed or open) for similar bug reports including closed ones
- [X] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [X] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [X] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**
`ia --version`
V 2.0.3
**Expected behavior**
Uploading to the Archive.

**Additional context**
Not sure if this is the same as S3 timeouts.

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\internetarchive\item.py", line 1071, in upload_file
    response.raise_for_status()
  File "c:\python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us.archive.org/youtube-14wc19ir4bk/14wc19ir4bk.description

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\tubeup\__main__.py", line 96, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "c:\python39\lib\site-packages\tubeup\TubeUp.py", line 386, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "c:\python39\lib\site-packages\tubeup\TubeUp.py", line 350, in upload_ia
    item.upload(files_to_upload, metadata=metadata, retries=9001,
  File "c:\python39\lib\site-packages\internetarchive\item.py", line 1240, in upload
    resp = self.upload_file(body,
  File "c:\python39\lib\site-packages\internetarchive\item.py", line 1097, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading 14wc19ir4bk.description to youtube-14wc19ir4bk, Access Denied - You lack sufficient privileges to write to this item.`

**Comment by brandongalbraith** [comment]
@Jenni32222 This error message indicates the item already exists: https://archive.org/details/youtube-14wc19ir4bk

We're tracking an issue to better handle these exceptions: https://github.com/bibanon/tubeup/issues/109
