### ISSUE TITLE
GUI support

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#185]
To attract a larger audience, use this tool to make a gui for the lesser experienced people. 
https://github.com/chriskiehl/Gooey

**Comment by TheTechRobo** [comment]
If this isn't added by the main project (which I think is probably going to be the case) I'll probably pick this up, but I won't use that tool. GTK programming is pretty easy in Python with PyGObject once you get the hang of it

**Comment by vxbinaca** [comment]
Thats actually exactly what I don't want to do. Attract a larger audience. IA guys already give me the stink eye every time I turn up in their inboxes.

**Comment by TheTechRobo** [comment]
Really? That surprises me.

Or do they want the URLs submitted to the WBM instead?

**Comment by vxbinaca** [comment]
Theres ~3 million youtube videos alone on Archive.org. Thats pretty good guys. We've got enough users and power users.

**Comment by brandongalbraith** [comment]
@TheTechRobo Feel free to extend this in your project, this isn't something we'd add to this fork.

**Comment by TheTechRobo** [comment]
thought so

**Comment by vxbinaca** [comment]
Right now I'm at ~200k YT alone and maybe another 30k Twitch videos. 

Internet Archive is a non-profit. Attracting a larger audience will lead to abuse to just wholesale dumps of Youtube which they're not equpiied to deal with.

Youtube like 7 years ago was adding 23 hours of video a second to the site. You can't get it all and jackasses who don't know any better will try to get it all, get up in the issues here complaining about writes to something already backed up.

Form a core of people and focus on one topic I'm not doing. Be dedicated.

**Comment by brandongalbraith** [comment]
Sorry for the brevity of my previous response, I'll go into a bit more detail to provide context.

Speaking only for myself, tubeup is intended to be a very specific tool: a media URL goes in, and all of the digital artifacts associated with the media are uploaded to the Internet Archive (media, metadata, captions, subtitles, etc). While I think there is value in digital archival audience expansion, I also think there's value in parties interested in using the tooling understand how and why the tool works. Abstractions should not hide power, but simplify its application.

With that said, I don't believe it's onerous to run tubeup from the command line, and I personally don't have the time to field support requests from non technical users (although other maintainers can chime in if they want to provide support to a non technical audience).

**Comment by vxbinaca** [comment]
yeah he's gotta deal with me already he doesn't need 50 worse me's
