### ISSUE TITLE
[feature request] Add command `--live-from-start`

### ISSUE THREAD

**Issue by FakeShemp** [bibanon/tubeup#186]
yt-dlp can now capture live streams off youtube from the beginning with the command `--live-from-start`. I think this should be the default behavior for tubeup.

**Comment by vxbinaca** [comment]
I'll look into it.

**Comment by pukkandan** [comment]
`--live-from-start` is currently experimental and still has some major bugs (https://github.com/yt-dlp/yt-dlp/issues/2137, https://github.com/yt-dlp/yt-dlp/issues/2898). These issues can be generally worked around (by the user) in various ways for single downloads. But for full automation, they can be a headache. I would honestly recommend holding off on implementing this for now

**Comment by vxbinaca** [comment]
Not to mention for Archival where we try to get it right the first time.

**Comment by vxbinaca** [comment]
Re-open this when that feature is no longer experimental and stable enough to bake in.
