### ISSUE TITLE
Bug report: wont install due to a to new internetarchive python libary on my system

### ISSUE THREAD

**Issue by www2000** [bibanon/tubeup#187]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [Problem] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [n/a] I've checked that all provided URLs are alive and playable in a browser
- [n/a] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [y] I've searched the issues (closed or open) for similar bug reports including closed ones
- [n/a] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [n/a] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [n/a] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**
Current relase
Please provide version information from core dependencies:
Wont install due to a new version IA tool that are on my system.
`ia --version`
internetarchive 2.2.0

**Expected behavior**
Install with the current relase of internetarchive python library

**Additional context**
Hi i have a dependesy problem with tubeup and ai tool.
ERROR: tubeup 0.0.27 has requirement internetarchive==2.0.3, but you'll have internetarchive 2.2.0 which is incompatible.

**Comment by vxbinaca** [comment]
pip3 install internetarchive==2.0.3
