### ISSUE TITLE
Garbage collection without interference

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#19]
REGEX needs to be used to do this.

Goals:

- Clean video and metadata from disk on upload
- Don't interfere with another instance of tubeups work. EX: one process is uploading a channel while another simultaneous instance is downloading it (max bandwidth utilization). So no quick and easy ```rm ~/.tubeup/downloads/*``` on exit.

**Comment by jjjake** [comment]
@vxbinaca I think we could use the `delete` parameter in `internetarchive.upload()` to deal with this (if I'm understanding it correctly).

When `delete` is set to `True` in the `upload()` call, the local files are deleted after the file has been successfully uploaded. Successfully uploaded means that the local md5 matches the md5 calculated by IA-S3 after the file has been handed off, and a 200 status is returned.

**Comment by vxbinaca** [comment]
@jjjake Yes that sounds like it would work quite well. 

My fiddling is literally done. I've cleaned up the comments and testing opts from when it was a script. So when you're ready I'll make a new version tag.

But then again, if you click on the link in your email, you can do that yourself if you'd like. You'll have write access to the repo.

**Comment by jjjake** [comment]
Awesome, sounds great @vxbinaca.
