### ISSUE TITLE
Add tubeup functionality to yt-dlp

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#190]
for yt-dlp, add a flag --upload-to-ia or --upload that uploads to the internet archive like tubeup dows. Add another flag, --delete-after-upload that deletes the files after it uploads it to the internet archive qualified. It will be a while until we catch up to YT-DLP, so just make a pull request.

**Comment by brandongalbraith** [comment]
Hi @upintheairsheep, the yt-dlp repo and issues is likely a better forum for proposing this enhancement.
