### ISSUE TITLE
Mirror yt-dlp options

### ISSUE THREAD

**Issue by JaxonPlays** [bibanon/tubeup#196]
Have every - or -- flag in tubeup.

Priorities for me is definitely --config-locations and --batch-file

**Comment by vxbinaca** [comment]
It's not a bug it's a feature. IA wants consistency in uploads and based on version they want to go back and look at what changes were made to tubeup and adapt deriving processes accordingly, or to just have consistency and sanity among uploads.

You can write your own batch files that use tubeup it's not terribly difficult.
