### ISSUE TITLE
Extract comments only

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#197]
Can you make a flag to extract comments only and upload it as youtubecomments-(video ID) (or (supported site name)comments-(Id)

This way the comments would be archived when the original video's comments weren't extracted.

Also when subtitles are added in the future, make a flag to archive them to (site)subs-(id)

**Comment by vxbinaca** [comment]
You'd have to own the item. You could whip up a script that does this easily.

**Comment by upintheairsheep** [comment]
I'm saying that because you don't own the item extract it as
(site)comments-(ID). That way it will make archiving comments possible
without archiving the video.

**Comment by vxbinaca** [comment]
Talk to the item owner.
