### ISSUE TITLE
Support Subtitles

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#198]
Can you add support for subtitles? For user subtitles, auto subtitles, and all languages. This includes live chat to be archived. Subtitles can be amazing if for some reason, YouTube (or another site) videos are endangered and there's too little storage to archive the videos themselves. This also has another use. The live chat is extracted this way which is really pog (for twitch, YouTube, and more).

**Comment by vxbinaca** [comment]
We support all subtitles except auto because "auto" isn't a language on Archive.org, and auto generated subtitles are low-quality and unreliable as a metadata type. IA scans items metadata for indexing and search results and including auto subs would pollute the search results on the site.
