### ISSUE TITLE
Feature Request: GitHub actuons

### ISSUE THREAD

**Issue by upintheairsheep2** [bibanon/tubeup#210]
Please make a GitHub action for tubeup use on iOS, which is the only operating system with no python as there's termux on Android and the only python apps are paid and the Linux apps are too slow for python. Basically this is Lecsu but your account is liable for uploading a lot, and tell archive team to not mention the action so it doesn't cause a "Lecsu situation".

**Comment by vxbinaca** [comment]
Take that up with them then. Stop making issues where you censor the URL and I can't test your problem, doing that is auto-close stuff. 

We're not Archive.org. I'm literally a some guy, a locksmith by profession, who has his own business and is not a employee of anyone. I volunteer here with my limited coding skills.

Your problem is either with IA messing with you, or the TikTok extractor is known to have problems, also IIRC the TikTok extractor doesn't support comments. Take that up with yt-dlp people not us. It's not our problem.

**Comment by upintheairsheep2** [comment]
> Take that up with them then. Stop making issues where you censor the URL and I can't test your problem, doing that is auto-close stuff.
> 
> We're not Archive.org. I'm literally a some guy, a locksmith by profession, who has his own business and is not a employee of anyone. I volunteer here with my limited coding skills.
> 
> Your problem is either with IA messing with you, or the TikTok extractor is known to have problems, also IIRC the TikTok extractor doesn't support comments. Take that up with yt-dlp people not us. It's not our problem.
> 
> None of these causes to your problem are our doing.

This is not a yt-dlp issue, I’m just requesting a GitHub actions setup that does tubeup. I put the yt-dlp issues in the yt-dlp issues. End of story for the yt-dlp issues.

**Comment by vxbinaca** [comment]
I'll look into it.

**Comment by vxbinaca** [comment]
Have you tried using a linux environment on iPhone that supports python/pip? That would probably fix whatever is ailing you.

**Comment by upintheairsheep2** [comment]
I used iSH and it was too slow. All the python apps are paid.

**Comment by vxbinaca** [comment]
Consider acquiring a cheap VPS with at least 100gb of storage, or paying for the python app. Alternatively get Termux on Android.

Perhaps this app may help you: https://apps.apple.com/us/app/pyto-python-3/id1436650069

**Comment by upintheairsheep2** [comment]
> Have you tried using a linux environment on iPhone that supports python/pip? That would probably fix whatever is ailing you.

Never mind. Just fix the existing items bug first.

**Comment by vxbinaca** [comment]
Which bug?

**Comment by upintheairsheep2** [comment]
The already existing item in archive.org causes it to fail bug. It’s just
annoying.

**Comment by vxbinaca** [comment]
It's not a bug, it's a feature. We don't want duplicate uploads. If you're going to dump a channel consider using yt-dlp to print out the video IDs on that channel and writing a batch script one by one, that way you can route around others uploads.

You dump channels at your own risk.

**Comment by upintheairsheep2** [comment]
I’m saying skipping duplicates. Not creating a big fat error while channel
archiving.

**Comment by vxbinaca** [comment]
I don't want to make it easier for people to fill up the Internet Archive with terabytes of Youtube. Because there are people who do not practice restraint, and just dump everything.
