### ISSUE TITLE
Feature Request: Add filter flags from yt-dlp

### ISSUE THREAD

**Issue by upintheairsheep2** [bibanon/tubeup#215]
The IA capacity problem may be fixed a little via adding the filter flags. If a long or large video is uploaded to IA, you can’t delete it or else no-one can upload it anymore forever. This will also make uploading short or small sized videos only easy. The IA will love these flags because large videos  are the cause of IA’s anger.

--playlist-start 
--playlist-end 
--playlist-items
--date                    
--datebefore
--dateafter
--match-filters
--max-filesize
(Min filesize not included due to being impractical)

**Comment by vxbinaca** [comment]
You fix the Archive.org capacity problem by not doing what you're doing, which you've expressed that you annoyed them.

You fix the capacity problem there by not implementing open ended YT-DLP flags. Which will never happen. I won't push a version to PyPi with them. No. You're endangering not just my work that I've worked on for 7 years but the work of others. Archive.org relies on a specific version of Tubeup to act a certain way. If we allow people to choose their own way of doing things they can't make fixes on a large scale.

Archive them to your own disk if thats what you want.

**Comment by vxbinaca** [comment]
Thats not something we can fix.
