### ISSUE TITLE
[Enhancement] Wrap tubeup with a web frontend

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#224]
Aspirationally similar to https://github.com/Tzahi12345/YoutubeDL-Material

**Comment by upintheairsheep** [comment]
Look what happened to Lecsu. IA will get mad and shut it down. If you are stuck with iOS that’s the only time to use web based

**Comment by upintheairsheep** [comment]
What OS Do you use

**Comment by vxbinaca** [comment]
will lead to abuse of IA and we'll be all cut off. Have self restraint because making it that easy will enable people to not have self restraint or accountability.

**Comment by vxbinaca** [comment]
@brandongalbraith please don't take that personally, we all work under the blessing of IA staff.
