### ISSUE TITLE
Use chat-downloader for twitch 

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#227]
Please use chat-downloader: https://github.com/xenova/chat-downloader on twitch automatically or add code to download twitch chats fully. If your not aware YT dlp has a bug.

**Comment by vxbinaca** [comment]
It already download Twitch chat as JSON but not a subtitle. Archive.org needs to get around to deriving all the Twitch items and mod their video player to be able to handle that. So it's already preserved.

**Comment by vxbinaca** [comment]
[Proof](https://archive.org/download/twitch-vod-v1536939533/v1536939533.rechat.json)

**Comment by vxbinaca** [comment]
Also we're not adding yet another piece of software for one specific site, software we have to reply on to be maintained by other devs. I'd rather have few dependencies.
