### ISSUE TITLE
Change directory and no delete commands

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#233]
Please add 2 commands that are helpful:

1. Default directory: This one is for the organization freaks out there, or external drive or NAS users. Please add a command to change the default tubeup directory called —folder .
2. —no-delete: This one prevents deletion of contents from the tubeup folder once it is already uploaded. The people who will use this are data “hoarders” or libraries who would like a copy of their data for their own sanity, especially those who downloaded large files or downloaded tons of comments.

**Comment by vxbinaca** [comment]
> 

Learn to use yt-dlp, downloading only is beyond the scope of the tool, this has been asked for for years and Tubeup only downloads, theres *zero* reason to hoarde using Tubeup. It's for quick scrapes with the best and most of everything. Not for hoardeing for later upload.

**Comment by vxbinaca** [comment]
If you want directories changed submit a PR as a flag that doesn't permanently change the directory.
