### ISSUE TITLE
Command shortcuts

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#234]
Command shortcuts are helpful, especially for people who frequently have typos or are forgetful of spelling. Currently the only command that has this is the help command.

 -m —metadata
  -h --help                 Show this screen.
  -x --proxy <prox>            Use a proxy while uploading.
  -u --username <user>         Provide a username, for sites like Nico Nico Douga.
  -p --password <pass>         Provide a password, for sites like Nico Nico Douga.
  -i --ignore-existing-item    Ignores the check for existing items on archive.org.
  -a --use-download-archive    Record the video url to the download archive.
                            This will download only videos not listed in
                            the archive file. Record the IDs of all
                            downloaded videos in it.
  -q --quiet                   Just print errors.
  -v --debug                   Print all logs to stdout.
  -o --output <output>         yt-dlp output 
template.
 -c —get-comments

**Comment by upintheairsheep** [comment]
-F folder
-k no delete
-f flat playlist

**Comment by upintheairsheep** [comment]
-l live from start

**Comment by vxbinaca** [comment]
> -l live from start

This. Flag. Is. Unstable. It. Is. Not. Suitable. For. Default. Use. Or. Even. As. A. Flag.

**Comment by upintheairsheep** [comment]
> > -l live from start
> 
> This. Flag. Is. Unstable. It. Is. Not. Suitable. For. Default. Use. Or. Even. As. A. Flag.

Ok. That was just a concept if that issue referencing it was accepted. Just add the rest of the flags

**Comment by vxbinaca** [comment]
You want descriptions of each flag in the default command output?

**Comment by vxbinaca** [comment]
>-F folder

No thanks. 

>-k no delete

Use yt-dlp for this 

>-f flat playlist

You can do yt-dlp flat playlist and then use that to build a playlist on archive.org based on the `videoID` element plus "youtube-" before the `videoID`.

**Comment by vxbinaca** [comment]
Shortcuts I can look into.

**Comment by upintheairsheep** [comment]
> -F folder -k no delete -f flat playlist

This issue is out of scope for these, this is just a concept if those features get approved.

**Comment by vxbinaca** [comment]
You need to learn to use yt-dlp flags seperatly from tubeup. `--flat-playlist` counts the videos on a channel, I don't see why thats useful to you. I'm not baking in yt-dlp flags and not allowing open-ended flags. Use yt-dlp for what yt-dlp does best. Tubeup cannot and will not do everything for you.

As for shortened flags, hit up in your app and erase the URL to do a rip with the flags yo want without typing all of it out. I'm not here to support mobile phones.
