### ISSUE TITLE
Flat playlists

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#235]
Add support for flat playlists. Otherwise we can’t archive playlist metadata if YouTube or some other video company does something to their playlists or their metadata. 

commands for archival: 

metadata 
yt-dlp —flat-playlist —write-info-json —write-all-thumbnails —write-json —write-comments

list of videos inside it
yt-dlp -j --no-warnings --flat-playlist "URL" | jq -r ".urls" > result.log

**Comment by vxbinaca** [comment]
No because we don't do the experience of playlists only the videos on the playlist. Archive.org has a playlist ability you can manually create.

**Comment by upintheairsheep** [comment]
> No because we don't do the experience of playlists only the videos on the playlist. Archive.org has a playlist ability you can manually create.

We have a ability to view images, including the profile picture and banner. Running the 2 commands downloads channel metadata only. Test it on a YouTube channel.

**Comment by vxbinaca** [comment]
Channel metadata isn't put on Archive.org, a channel can be rebuilt using creator name and creation dates.
