### ISSUE TITLE
Automatically get comments without --get-comments if fewer than 500 comments

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#248]
Most "tubeuppers" do not use the get comments flag when downloading the videos, therefore causing loss of comments of those videos, which usually have less than 500 comments. If it has more than 500 comments, the --get-comments flag should be required due to the length it takes to archive them. You also should print yt-dlp's comment progress without having to use the --debug flag.

**Comment by vxbinaca** [comment]
Use the flag if you want comments.

**Comment by vxbinaca** [comment]
Comments are apart of the experience of the Youtube website, which we do not by default grab. This is a VIDEO (and associated metadata) mirroring application. Archive.org does not have an ability to display the comments. The comments are not generally part of the video in question being posted. and frankly and this is a subjective view, the comments are the worst part of the site. Let the wayback machine grab them. This is a scope thing.

**Comment by gabldotink** [comment]
The Wayback Machine does not grab comments. More of my two cents about this opinion on what to archive is [here](https://github.com/bibanon/tubeup/issues/252#issuecomment-1291492971). If others agree with me on this, this might be an issue worth reopening.
