### ISSUE TITLE
Add --get-pages ( -g )

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#257]
Hello, the --write-pages command in yt-dlp downloads the API json files it encounters while keeping the basename, however cannot usually be grabbed via wayback machine due to needing a specific user agent or cookie. This is useful on TikTok, as the info json files lack most data, and TikUp, the tool to archive tiktok had the functionality to dump the original json by default.

**Comment by vxbinaca** [comment]
No. Read the yt-dlp readme on how to get video IDs and rip those, or I will ban you from this project and any new accounts you make. Do not test my stamina on this it's greater than yours.

Here's what we're gonna do: I'm giving you a 1 month break Tubeup. Do not make any issues even for legitimate bugs (that I will likely catch before you do), or I will ban you from this project. 

Do not ever again ask for something that is in the yt-dlp readme. Ever.
We are not adding new flags. 
We are not enabling open flags for yt-dlp. 
We are not your tech support for 'yt-dlp' or `internetarchive`
We are not easing Tubeup use on mobile phones.

Yt-dlp is the downloader for videos, not Tubeup. Stop, STOP, asking us to add flags or open up flags.

You will learn to use yt-dlp outside Tubeup, or you will not get support for Tubeup. 

Your 1 month break starts today. I'll see you December 1st. Do not make another issue until then. 


re: your other issue: You need a Netscape formatted cookies file. Use a extension to get that. This is the last ever tech support issue I answer for you ever.

Do you understand?

**Comment by upintheairsheep** [comment]
And I’ll take the break

**Comment by upintheairsheep** [comment]
I understand how I have made nonsensical and out of scope issues, sorry about that. I accept the break. Can I make pull requests to add playlist filters from yt-dlp? I will try stop and think before making a feature request next month, if I even have any.

**Comment by vxbinaca** [comment]
No you can use yt-dlp to process youtube or other sites and then take the result and plug it into tubeup it's not that hard.  I think this is the 9th time I've told you this.

Tubeup is too complex and I actually am thinking of other things to remove to reduce complexity.

We cannot support workarounds for yt-dlps broken TikTok extractor or comments. Fork Tubeup if you don't like it, or cope that the history will just have to be lost I've had to do it for other things. We prize stability here. Note that forking tubeup won't fix TikTok, your efforts would be better spent working on TikToks extractor or coming up with a good javascript solution. Selenium and Puppeteer are good candidates.

But we will not be doing site specific hacks or support here.

**Comment by vxbinaca** [comment]
Do you understand what I mean when I say use yt-dlp to extract video IDs from sites @upintheairsheep? Are you going to stop asking for flags to tubeup for things yt-dlp does? do you understand the consequences if you fail one more time to use yt-dlp and ask for a new flag?
