### ISSUE TITLE
Directory for Videos

### ISSUE THREAD

**Issue by xrizonx** [bibanon/tubeup#262]
Hi,

Would it be possible to implement custom location for videos to be stored that have to be uploaded. Do not want my SSD to be filled when i have ample storage on my old mechanical drives.

Thanks!

**Comment by vxbinaca** [comment]
Please consider using a VPS, or a VM thats pointed to a different disk.

**Comment by vxbinaca** [comment]
if you or someone can come up with a PR that doesn't break things, perhaps for a configuration file for Tubeup, or a flag to point to a new directory, I'd merge it. But it can't break any existing features.

**Comment by vxbinaca** [comment]
Actually on third thought, we have enough flags. Please consider getting a VPS to rip. If you're ripping big things, consult Archive.org first lest you want ban troubles. 

We just got done adding flags for a simple rip tool. This is a simple tool. Simple. It's supposed to upload a video quickly.

**Comment by upintheairsheep** [comment]
Edit the Tubeup code and change “dir-path” to your choice. That helped me.

**Comment by xrizonx** [comment]
Hi,

Thanks for the feedback what i ended up doing was creating a hardlink to a different drive in the default directory that way no traffic hits the primary SSD.

Seems to be working ok.
