### ISSUE TITLE
Bug report: Item Exists output should output item URL not video URL

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#264]
`tubeup jNQXAC9IVRw`

Outputs this:
```
:: Item already exists. Not downloading.
Title: Me at the zoo
Video URL: https://www.youtube.com/watch?v=jNQXAC9IVRw
```

When it should be outputting this:

```
:: Item already exists. Not downloading.
Item URL: https://archive.org/details/youtube-jNQXAC9IVRw
```

Edit:

If this is this way for a reason, comment here and I will close.

**Comment by mrpapersonic** [comment]
I made it this way so it would be faster to debug whether an item actually existed or not while testing it. It can be changed to the former layout if you want.

**Comment by vxbinaca** [comment]
No thats fine. Closing. Disregard.
