### ISSUE TITLE
.netrc + general auth for sites

### ISSUE THREAD

**Issue by speakeasy** [bibanon/tubeup#27]
This is a feature request to download a users viewing history (Watch Again) list using oauth or some form of password/cookie auth.

**Comment by vxbinaca** [comment]
Isn't this public if you set it? 

Youtube-dl has a flag for using ```.netrc```, so unless you're using 2-auth, this is the best bet. It'd just need to be turned into a flagable thing within tubeup.

**Comment by vxbinaca** [comment]
No .netrc but we do have auth now. Closing.
