### ISSUE TITLE
Bug report: Rate limiting is not implemented

### ISSUE THREAD

**Issue by savchenko** [bibanon/tubeup#275]
**Checklist**

- [x] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

```
tubeup v0.0.35
ia v3.2.0
youtube-dl v2021.12.17
```

**Expected behavior**
I would expect `tubeup` to have a flag that allows to set the upload timeout. For example
```sh
$ tubeup --upload-timeout=60 "https://youtube.com/@foo" # Wait 60s between video uploads
```

**Actual behavior**
`tubeup` uploads next video as soon as possible. This results in interrupted upload and program exit with `HTTPError`:

```sh
[DEBUG] 2023-01-28 18:14:45,407 - internetarchive.item - ERROR -  error uploading foo.webp to youtube-bar, Please reduce your request rate. - Your upload of youtube-bar from username baz@example.net appears to be spam. If you believe this is a mistake, contact info@archive.org and include this entire message in your email.
```

Traceback:
```
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/internetarchive/item.py", line 1055, in upload_file
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Slow Down for url: https://s3.us.archive.org/youtube-foo.webp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/user/.local/lib/python3.9/site-packages/tubeup/TubeUp.py", line 421, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/user/.local/lib/python3.9/site-packages/tubeup/TubeUp.py", line 383, in upload_ia
    item.upload(files_to_upload, metadata=metadata, retries=9001,
  File "/home/user/.local/lib/python3.9/site-packages/internetarchive/item.py", line 1222, in upload
    resp = self.upload_file(body,
  File "/home/user/.local/lib/python3.9/site-packages/internetarchive/item.py", line 1080, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
```

Given that InternetArchive explicitly instruct client to "slow down for url", one would expect the client to follow the instruction and introduce a delay.

**Additional context**
This does not seem to be related to https://github.com/bibanon/tubeup/issues/91 and similar ones, but **it is** related to https://github.com/jjjake/internetarchive/issues/298

Repeated upload after some time resolves this issue for the failed item, _however_...

What makes this issue particularly problematic is that successful uploads are deleted upon once they are verified to be successful. For example:
```
[DEBUG] 2023-01-28 18:11:30,841 - urllib3.connectionpool - DEBUG - https://s3.us.archive.org:443 "PUT /youtube-foo/foo.webp HTTP/1.1" 200 0
[DEBUG] 2023-01-28 18:11:30,842 - internetarchive.item - INFO - uploaded foo.webp to https://s3.us.archive.org/youtube-foo/foo.webp
[DEBUG] 2023-01-28 18:11:30,842 - internetarchive.item - INFO - foo.webp successfully uploaded to https://archive.org/download/youtube-foo/foo.webp and verified, deleting local copy
```
Then, once the 503 is issued by the server, user has to re-download now missing artefacts only to skip them later as the items are already uploaded to IA.

**Comment by vxbinaca** [comment]
Closing because:

You censored the video output. I cannot tell the site or URL you ran this on. Do not waste our time hindering diagnosing problems.

Whatever you're doing you need to slow it using a external time delay command that we will not be implementing.

>Given that InternetArchive explicitly instruct client to "slow down for url", one would expect the client to follow the instruction and introduce a delay.

We don't know what that is. They don't tell us. It's their service they can throttle or ban you for dumping channels. I've had both happen to me. We're not here to help you get around it.

If you read the front page it tells you channel dumping can be considered abusive. Whatever it is you were dumping - which you've hidden from us - was considered to be a burden to IA.

>What makes this issue particularly problematic is that successful uploads are deleted upon once they are verified to be successful. 

They are deleted once uploaded to IA. Yes. Thats a feature. So once it's on IA it's not needed on the users disk. If it's been uploaded to IA then you don't need the local copy. Tubeup is a mirroring application. If you want a local copy kept use yt-dlp.
