### ISSUE TITLE
Bug report: Twitch chat at some point stopped being downloaded (RECHAT)

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#276]
I'll investigate this over the next few days

**Comment by vxbinaca** [comment]
Johnny on the spot with that tag thank you VERY much Bran. Okay so we'll wait for a extractor fix this is why I advocate for separation of powers, this isn't a us problem.

**Comment by upintheairsheep** [comment]
Anyways, there is a workaround:
pip install chat-downloader
chat_downloader -o {id}.json INSERTURLSHERE

Then upload it to the internet archive

**Comment by vxbinaca** [comment]
Yeah I would rather yt-dlp be fixed than add yet another dependency.

**Comment by vxbinaca** [comment]
> 

How generous of you. I say yt-dlp because how it does it is a reliable and expected way of doing things.
