### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by pedroalmeida415** [bibanon/tubeup#278]
For some reason I keep getting this same error for any video that I try to upload:

`ERROR: [youtube] ymGNkqLMrJg: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/nameless/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/nameless/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 4049, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/nameless/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)`

`An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/nameless/.local/lib/python3.8/site-packages/tubeup/__main__.py", line 99, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/home/nameless/.local/lib/python3.8/site-packages/tubeup/TubeUp.py", line 417, in archive_urls
    downloaded_file_basenames = self.get_resource_basenames(
  File "/home/nameless/.local/lib/python3.8/site-packages/tubeup/TubeUp.py", line 172, in get_resource_basenames
    if info_dict.get('_type', 'video') == 'playlist':
AttributeError: 'NoneType' object has no attribute 'get'`

Could someone help me sort this out?

**Comment by pedroalmeida415** [comment]
Yes, I do

Also, just saw another issue opened with this exact error on yt-dpl repo, doesn't seems to be a problem with tubeup so I'll be closing this.

Refer to: https://github.com/yt-dlp/yt-dlp/issues/6253

**Comment by vxbinaca** [comment]
Discontinue use of Tubeup on the youtube extractor for the next 10 hours unless it is one video or an emergency. Check output of each item you creator from that site for the next 10 hours.

**Comment by vxbinaca** [comment]
yt-dlp has [merged](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) a fix, if you use a bleeding edge build you should be able to within the next few hours take advantage, and whenever they cut a new version everyone else will, for something like this I'd imagine they'll cut tomorrow or sooner.

**Comment by vxbinaca** [comment]
@pedroalmeida415 yt-dlp was updated
