### ISSUE TITLE
Proposal: Add option to change download priority

### ISSUE THREAD

**Issue by Defog7277** [bibanon/tubeup#282]
I tried to download Youtube livestream that was currently running using command: `tubeup url`

Unfortunately, instead of starting with downloading the video, the program started downloading the livechat first

At the same time it displayed a message about separete instance

I started the second instance and the effect was the same, the program downloaded livechat instead of the video.

Normally I would wait for the stream to finish and then download the full livestream with chat.
Unfortunately the youtubers I watch immediately set the videos as private after the streaming ends or delete the videos completely. So the option with waiting for the livestream to end is not an option.

Is there an option to change the download priority in Tubeup? So that when I type the command, the program starts by downloading the video file and not the chat?

**Comment by vxbinaca** [comment]
Closed because you didn't read the submission guidelines and just deleted everything without reading it. Please re-submit and follow the guidelines.
