### ISSUE TITLE
Bug report: extremely slow downloads from youtube

### ISSUE THREAD

**Issue by 111100001** [bibanon/tubeup#287]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [y ] I have fully updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies.
- [y ] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). Hiding URLs will get issue closed.
- [y ] I've checked that all provided URLs are alive and playable in a browser
- [y ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ y] I've searched the issues (closed or open) for similar bug reports including closed ones
- [ y] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [y ] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [ y] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

`ia --version`  3.0.2
`yt-dlp --version` 2023.03.04

**Expected behavior**

downlods form youtube should be downloaded faster than 20 kb/s , it seems that youtube is throttling the downloads, i hve found the solution on yt-dlp https://github.com/yt-dlp/yt-dlp/issues/7150  , but i don't know how to apply that solution to tubeup

**Additional context**

download speed has been like this for a whole day.
[download]   8.5% of        N/A at   39.88KiB/s ETA 43:03:59

**Comment by 111100001** [comment]
UPDATE: THE ISSUE SEEMS TO BE VIDEO-SPECIFIC , i tried  different video form the same channel and the download speeds were fine, it's just one video that is slow in downloads, here is the video https://www.youtube.com/watch?v=Inm-hegcRdQ

**Comment by vxbinaca** [comment]
Closed due to not filling out the issue template properly. Read about what to put in the boxes. You didn't give your command or terminal output.

So slow down and read the issue template better next time, and read the terminal output where it tells you certain formats will be throttled.

**Comment by 111100001** [comment]
i read the issue template completely, there is nothing that says anything about throttling in the terminal output, it's just shows the download speed are stuck at around 20kb/sec 

the command is: 

`tubeup https://www.youtube.com/watch?v=Inm-hegcRdQ`

for some reason, this video is throttled when  tubeup downloads it, the other videos are downloading fine without throttling,

**Comment by vxbinaca** [comment]
@111100001 

World changing idea: Tubeup does not download the video. I mean it. Really. Tubeup uses library calls for yt-dlp and it downloads the video. The terminal output tells you certain formats like the ones tubeup requires are throttled, and you deleting your reply tells me you only read the terminal output AFTER replying.

Furthermore, at the top of the issue template say this at the top of it:

`put x into all relevant boxes (like this [x]`

You put Ys in the boxes, so it messes up the template. Your videos are going at what, was it you said, 20kbps? So it looks like you have the time to read things like terminal output and the issue template guidelines here.

Locked.
