### ISSUE TITLE
Bug report: [native] nsig extraction failed

### ISSUE THREAD

**Issue by oti4500** [bibanon/tubeup#290]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [x] I have fully updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies.
- [x] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). Hiding URLs will get issue closed.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

`ia --version` 3.0.2
`yt-dlp --version` 2023.03.04

**Expected behavior**
Archiving the entire YouTube channel after launch.

**Additional context**
PhantomJS installed. All things installed.

**Problem**
First attempt:
tubeup --metadata=collection:opensource_video  https://www.youtube.com/@Partizanmedia --use-download-archive 
[youtube] Xg24-e4MCYU: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Bprqdi-6PcRlIgQ-hd ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js
[youtube] Xg24-e4MCYU: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = O3aqVz25nJKNeBh3BM ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js

After I installed the PhantomJS.

Second: 
tubeup --metadata=collection:opensource_video  https://www.youtube.com/@Partizanmedia --use-download-archive 
[youtube] ZmxmqZZvIcY: Native nsig extraction failed: Trying with PhantomJS
         n = F7SrdQkxNbI6m9G6SR ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js
[youtube] ZmxmqZZvIcY: Native nsig extraction failed: Trying with PhantomJS
         n = 1kJiF5vkAlBYE_C07y ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js

Third:
tubeup --metadata=collection:opensource_video https://www.youtube.com/@Partizanmedia/videos --use-download-archive 
[youtube] ZmxmqZZvIcY: Native nsig extraction failed: Trying with PhantomJS
         n = m3GZF4ed6cqbiMP-J7 ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js
[youtube] ZmxmqZZvIcY: Native nsig extraction failed: Trying with PhantomJS
         n = AegBBaAFxNOglo7maY ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js

**Comment by vxbinaca** [comment]
Closed for:

- Not indenting terminal output as instructed
- [We can't control this behavior it's a yt-dlp issue](#289)

**Comment by oti4500** [comment]
And? Thats how working?
yt-dlhttps://www.youtube.com/@Partizanmediaia
[youtube:tab] Extracting URL: https://www.youtube.com/@Partizanmedia
[youtube:tab] @Partizanmedia: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @Partizanmedia/streams: Downloading webpage
[youtube:tab] @Partizanmedia/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUEFpEvuosfPGlV1VyUF6QOA
[download] Downloading playlist: Partizán
[youtube:tab] Playlist Partizán: Downloading 3 items of 3
[download] Downloading item 1 of 3
[download] Downloading playlist: Partizán - Videos
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 1: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 2: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 3: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 4: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 5: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 6: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 7: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 8: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 9: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 10: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 11: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 12: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 13: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 14: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 15: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 16: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 17: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 18: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 19: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 20: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 21: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 22: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 23: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 24: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 25: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 26: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 27: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 28: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 29: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 30: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 31: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 32: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 33: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 34: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 35: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 36: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 37: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 38: Downloading API JSON
[youtube:tab] UCEFpEvuosfPGlV1VyUF6QOA page 39: Downloading API JSON
[youtube:tab] Playlist Partizán - Videos: Downloading 1176 items of 1176
[download] Downloading item 1 of 1176
[youtube] Extracting URL: https://www.youtube.com/watch?v=20ptT8DAGvc
[youtube] 20ptT8DAGvc: Downloading webpage
[youtube] 20ptT8DAGvc: Downloading android player API JSON
[info] 20ptT8DAGvc: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 13
[download] Destination: A nagy műanyaghazugság ｜ az Investigate Europe és a Partizán első közös videója [20ptT8DAGvc].f248.webm
[download]  67.7% of ~ 130.00MiB at   18.26MiB/s ETA 00:02 (frag 8/13)

**Comment by vxbinaca** [comment]
[Learn how to indent your terminal output. ](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)

Locked.
