### ISSUE TITLE
Possible NSIG fixes

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#291]
Youtube has done a incomplete rollout of a new player, and the [new player isn't compatible with yt-dlps current stable release](https://github.com/yt-dlp/yt-dlp/issues/6131) on pip and to me it seems YT is doing it to break compatibility on purpose. Some videos work, some don't and they're a newer player that yt-dlp hasn't adapted to.

PhantomJS is dead software, it's repo is archived. Selenium or Puppeteer (I think) would be better choices but that's for yt-dlp to decide.

I see two fixes: 

- Instruct users to compile/install Tubeup off-Pip and have them use yt-dlp nightly builds, I think `path` magic would need to be done to get them to see one another.
- Remove `--best-video` and `--best-audio` flags from configs might allow in some cases a format thats not throttled, the downside is the best quality streams are not grabbed and frankly even though that fix is easy the side effects aren't acceptable even though I'm currently getting videos that NSIG doesn't just throttle but it prevents the rip.

I'm open to comments

**Comment by vxbinaca** [comment]
> There a yt-dlp issue tracking this by chance? If so, can you drop the link here?

[This is a good start.](https://github.com/yt-dlp/yt-dlp/issues/6131)

**Comment by vxbinaca** [comment]
I may have a fix, we'd have to instruct people to run this:

```
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev -y
sudo apt-get install libfreetype6 libfreetype6-dev -y
sudo apt-get install libfontconfig1 libfontconfig1-dev -y
cd ~
export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2
sudo tar xvjf $PHANTOM_JS.tar.bz2
sudo mv $PHANTOM_JS /usr/local/share
sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
export OPENSSL_CONF=/dev/null
phantomjs --version
```

Both of those exports would need to be appended onto the shells rc file (bashrc or in my case zshrc) for two reasons:

- The first is to enable yt-dlp to see PhantomJS, and the second is to kill a SSL conf bug thatstops PJS from running. 

I've followed the above steps, sans EXPORT rc appends, and it seems to be working.

**Comment by 111100001** [comment]
i  will be implementing this to my vm and see if it is working. thank you.

**Comment by mrpapersonic** [comment]
No, it's because you're trying to run an x86_64 binary on ARM64.

**Comment by vxbinaca** [comment]
Update yt-dlp to latest stable release as [NSIG extraction for F17 was fixed](https://github.com/yt-dlp/yt-dlp/commit/c9abebb851e6188cb34b9eb744c1863dd46af919), see if that stops the problems.
