### ISSUE TITLE
"Creator" field for Douyin needs update

### ISSUE THREAD

**Issue by xuen97** [bibanon/tubeup#294]
I find that when uploading videos from Douyin using TubeUp, the "creator" field is set to `vid_meta['uploader_url']` instead of `vid_meta['creator']`. A way to fix this is by changing line 477 in `TubeUp.py` to `if (vid_meta['extractor_key'] == 'TwitchClips' or vid_meta['extractor_key'] == 'Douyin') and 'creator' in vid_meta and vid_meta['creator']:`.

**Comment by vxbinaca** [comment]
@brandongalbraith extractor bug or us?

**Comment by vxbinaca** [comment]
@brandongalbraith I want to mark this as unfixable by us for a few reasons:

- Douyin is chinese domestic TikTok
- CCP state security org backdoors Douyin and requires login to spy on it's citizens, forcing cookie use to test, and the site heavily pushes you to the app.
- A mis-pointed creator tag is a yt-dlp extractor problem. They need to fix extractor to point it right to even supply it (BilliBilli is another weird chinese site that for ex. has no channels attribute either has no channel attribute in metadata and/or it's not supplied in extractor)

Your thoughts?

**Comment by vxbinaca** [comment]
Here's a example Douyin rip that used Tubeup:

[https://archive.org/details/Douyin-7253745247807704372](https://archive.org/details/Douyin-7253745247807704372) (does not resolve)

Source of the rip: [https://www.douyin.com/video/7253745247807704372](https://www.douyin.com/video/7253745247807704372)

Creator name on IA item: [铁骨曾曾](https://archive.org/search.php?query=creator%3A%22%E9%93%81%E9%AA%A8%E6%9B%BE%E6%9B%BE%22)
Creator URL that corresponds with the IA listing: [铁骨曾曾](https://www.douyin.com/user/MS4wLjABAAAA1SAPKSuR58bqVOq2fJeEvaIk9BPViKA6Zz2z7I3Nfu4)

Creator names match creator on Douyin.

Closing unless @xuen97 specifies the problem better then I'll re-open.

**Comment by xuen97** [comment]
I know it needs cookies, so I would visit the site and extract the cookies each time I want to upload a video from Douyin. However, the reason why I'm posting this is because I would like to suggest a change in the `TubeUp.py` file to account for Douyin videos. The reason why the creator name seems to match in the above example is because I have updated the creator name myself manually. Otherwise, the creator field will be the same as the channel field.

**Comment by vxbinaca** [comment]
> I know it needs cookies, so I would visit the site and extract the cookies each time I want to upload a video from Douyin. However, the reason why I'm posting this is because I would like to suggest a change in the `TubeUp.py` file to account for Douyin videos. The reason why the creator name seems to match in the above example is because I have updated the creator name myself manually. Otherwise, the creator field will be the same as the channel field. I tried editing it on my local version of the file and it works.

That confirms that the Douyin extractor in yt-dlp has a issue not us, but you're still not out of the woods yet.

The items I linked to were all uploaded with 0 problems. As I showed, the item from yesterday has matching creator tags to whats on the Douyin profile. Are you using a up-to-date yt-dlp?

**Comment by vxbinaca** [comment]
Story straight:

[We have a bug submission form](https://github.com/bibanon/tubeup/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=Bug+report%3A+), that you bypassed, ignored, missed or blanked out, then you post the question but then tag as bug shortly after.

Brandon and I have asked for specific commands, version numbers, or example problem uploads. Skimming the Internet Archive for Douyin rips, I have found none in a page or so of examples.

Please re-submit this issue as a bug, follow the instructions read every line and follow it's instructions.
