### ISSUE TITLE
Update internetarchive to 3.4.0/3.5.0?

### ISSUE THREAD

**Issue by zoktiik** [bibanon/tubeup#295]
Currently, the Tubeup package requires that `internetarchive==3.0.2`:
```
ERROR: pip's dependency resolver does not currently take into account all the pa
ckages that are installed. This behaviour is the source of the following depende
ncy conflicts.                                                                  
tubeup 2023.5.29 requires internetarchive==3.0.2, but you have internetarchive 3
.5.0 which is incompatible.    
```
Is there any particular reason why Tubeup requires this version of `internetarchive`?

**Comment by vxbinaca** [comment]
I do not know how something so simple was overlooked by me. I am pushing a new version in a few minutes that lifts the requirement. We version locked it years ago because of a config location thing but it should have been lifted years ago.

Apologies for missing this one.

**Comment by vxbinaca** [comment]
New versions is cut boys, it's working. We're golden now on this front.

**Comment by vxbinaca** [comment]
@zoktiik again, my apologies on missing this. Either I neglected to lift this years ago, or it regressed due to having a stale repo on my end. Either way that dragon is now slayed.

@brandongalbraith let's work together sometime to lift the other dep locks.
