### ISSUE TITLE
Uploaded YT video thumbnails in .webp are not used for IA item tiles

### ISSUE THREAD

**Issue by zoktiik** [bibanon/tubeup#296]
Lots of Youtube channels have been uploading their own thumbnails to provide more visual context than what can be conveyed through the video's title alone. Currently, Tubeup does get the thumbnail and uploads it to the item on IA, but (I assume) it is not usable as the item tile, and so IA automatically `derive`s a thumbnail from a random frame in the video instead.

My first assumption as to the cause of this would be that Youtube video thumbnails are in `.webp` format, and to use them for tiles on IA would require that they be converted (as a copy) to `.jpg` format.
The issue could also potentially be caused by the images not being set as "Item Tiles", but when attempting to do this to the webp, IA seems to always prefer its own auto-generated thumbnails added through the `derive` task, so it's more likely the former. It could be both at the same time, I don't know.

**Comment by zoktiik** [comment]
@brandongalbraith Looking at other items for Youtube videos that have the proper thumbnails in place, I found one that has the original-size, 1280x720 thumbnail in `jpg` format, with `derive` seeming to prefer and use that instead of the video. The only thumbnail that IA (logically) seems to respect is the 180px-or-below `__ia_thumb.jpg`.

What this means is that seemingly, all that needs to be done is to convert a copy of the `.webp` thumbnail image to `.jpg`, and IA will simply `derive` a thumbnail from that. 
You could maybe do `.png` instead, but I don't know if that would be particularly worth it.

Here's the item I am basing my conclusions off of:
https://archive.org/details/youtube-L2xMi7inB28
![image](https://github.com/bibanon/tubeup/assets/50035052/ec10f1dc-9cbe-4f9f-805e-7bd890dbe032)

**Comment by vxbinaca** [comment]
Youtube gives us .webp. They still give us VTT subs and IA corrected their web player to account for it. I don't want to force formats that either take up more space, degrade quality, change what was given or require more deps.

**Comment by zoktiik** [comment]
Sent an email to info@IA informing the staff about the .webp derive issue. Hopefully they read it, and are able to resolve this on their side.
However, in the interim, options for new uploads that want to include the thumbnail are highly limited/inconvenient. Is there any possibility for some sort of temporary workaround?

**Comment by vxbinaca** [comment]
Theres no reason extra data needs to be made for this operation, or we need to re-encode the images. WebP is absolutely capable of being used on their end with a minimal code change in the derive scripts.

**Comment by vxbinaca** [comment]
>You could maybe do .png instead, but I don't know if that would be particularly worth it.

That generates extra data because PNGs would IIRC need to be derived, PNGs weigh more.
