### ISSUE TITLE
Provide --username and --password to youtube-dl via Tubeup

### ISSUE THREAD

**Issue by antonizoon** [bibanon/tubeup#30]
We should make two arguments that pass a username and password to tubeup, as some services require login. 

Some services also used to allow nonlogin scraping (such as niconico), but they're having issues with that, so we need to be able to log in. 

Example youtube-dl command;

```
youtube-dl --username "user@email.com" --password "your_password" --write-annotations --write-description --write-info-json --write-thumbnail URL
```

**Comment by dkl3** [comment]
Any updates on this?

**Comment by vxbinaca** [comment]
@antonizoon provided for this in the last update. Closing his issue.
