### ISSUE TITLE
Bug report: Unable to archive Youtube video after premiere

### ISSUE THREAD

**Issue by Exorcism0666** [bibanon/tubeup#309]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [x] I have fully updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies.
- [x] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). Hiding URLs will get issue closed.
- [x] I've checked that all provided URLs are alive, playable in a browser and arguments with special characters are properly quoted or escaped.
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I'm not submitting a bug report about IA S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I'm not submitting a bug report about NSIG timeouts (this is beyond tubeups control and is a yt-dlp issue)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).
- [x] I am putting all of the required information in the original issue post and not adding it to a following comment.

**Dependency versions**

Please provide version information from core dependencies:

`ia --version = 3.5.0`
`yt-dlp --version = 2023.07.06`

**Expected behavior**
If a Youtube video was published as a premiere, it will be impossible to archive it after the premiere.

![Screenshot_2023-08-29-08-37-06-58_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/bibanon/tubeup/assets/46537034/7a5124ef-2d1c-4149-8b69-d42b64f298f6)

you can try to archive with these two urls, normally tubeup should not work: https://youtu.be/n4Y0Ku9DJ90 , https://youtu.be/BVsydk6SFV8

**Comment by vxbinaca** [comment]
Not a tubeup bug. You didn't follow indent guidelines on pasting terminal output and indenting, no, screenshots are not acceptable in the bug report.

![image](https://github.com/bibanon/tubeup/assets/12656590/456b6fae-2069-4101-bd3b-1bed08ebdc27)
