### ISSUE TITLE
Archiving stops after few youtube-dl copyright ERROR messages

### ISSUE THREAD

**Issue by rudolphos** [bibanon/tubeup#31]
So I was archiving and then like 4 messages showed up of something like this

```
ERROR: xxx: YouTube said: This video contains content from FranceTV mcn, who has blocked it on copyright grounds.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1327, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: xxx: YouTube said: This video contains content from FranceTV mcn, who has blocked it on copyright grounds.

root@xxx:~# 
```
And the download/archiving process cancelled..

I entered those 4 ID's manually into .ytdlarchive file, but then it just didn't work at all for this particular channel.

```
root@xxx:~# tubeup https://www.youtube.com/channel/xxx
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 3.5.2+ - Linux-4.8.0-30-generic-x86_64-with-Ubuntu-16.10-yakkety
[debug] exe versions: avconv 3.0.2-1ubuntu3, avprobe 3.0.2-1ubuntu3, ffmpeg 3.0.2-1ubuntu3, ffprobe 3.0.2-1ubuntu3
[debug] Proxy map: {}
[debug] Public IP address: 2001:4xxx
root@xxx:~#
```

And the channel was not archived completely, I had uploaded only 15% on archive.org the rest 85% can't be done because of these ERRORs.

And what about cancelling (by cancelling I mean closing putty window) a download I have done that on other channels. It should resume DL from the last fragment, but sometimes it has recorded all the ID's in the .ytdlarchive file as already downloaded and downloads are not starting again for that channel .... It just downloads the newest videos from the channel.

I'm also now reading this

`        'download_archive': os.path.expanduser('~/.tubeup/.ytdlarchive'), ## I guess we will avoid doing this because it prevents failed uploads from being redone in our current system. Maybe when we turn it into an OOP library?
`

That's exatcly what is happening

> it prevents failed uploads from being redone in our current system

cancelled archiving proceess = failed uploads
And so I can't redone them, other than deleting the .ytdlarchive file ?

If I delete it, I bet there are gonna be created/downloaded files again with _(1) at the end. And I don't want that..

**Comment by antonizoon** [comment]
@vxbinaca Maybe we should try to catch ExtractorErrors so we can note them down then continue. This way the script can state which urls failed at the end, instead of just crashing.

**Comment by vxbinaca** [comment]
@antonizoon @rudolphos Would '--ignore-errors' on youtube-dl side fix this?

**Comment by vxbinaca** [comment]
@rudolphos I would suggest hand editing the archive file to delete everything after the last successful upload. Although if there was an error for copyright, that particular video ID isn't archived. Anything after it, it will get.

**Comment by rudolphos** [comment]
@vxbinaca 

> hand editing the archive file to delete everything after the last successful upload

There are multiple archive files, like 80 or more..
By delete everything you mean 1 video file and those other types of subtitles and jpegs ?


Just tried it on the latest uploaded item, but nothing happened. Tried it 2 times.


```
root@nsxxxx:~# tubeup https://www.youtube.com/user/xxxx
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 3.5.2+ - Linux-4.8.0-30-generic-x86_64-with-Ubuntu-16.10-               yakkety
[debug] exe versions: avconv 3.0.2-1ubuntu3, avprobe 3.0.2-1ubuntu3, ffmpeg 3.0.               2-1ubuntu3, ffprobe 3.0.2-1ubuntu3
[debug] Proxy map: {}
[debug] Public IP address: 2001:xxx
root@ns378482:~# tubeup https://www.youtube.com/user/xxxx
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.12
[debug] Python version 3.5.2+ - Linux-4.8.0-30-generic-x86_64-with-Ubuntu-16.10-               yakkety
[debug] exe versions: avconv 3.0.2-1ubuntu3, avprobe 3.0.2-1ubuntu3, ffmpeg 3.0.               2-1ubuntu3, ffprobe 3.0.2-1ubuntu3
[debug] Proxy map: {}
[debug] Public IP address: 2001:xx
root@nsxxxx:~#

```

**Comment by vxbinaca** [comment]
It sounds like a lot of videos on this channel are copyright blocked in certain countries. Try using a VPS/VPN?

**Comment by vxbinaca** [comment]
I mean, go into the archive file that record your progress ( ~/.tubeup/.ytdlatchive ), go look at your Archive.org uploads, find the last successful complete upload:

```https://archive.org/details/youtube-zX7Q_8eobSU```

Okay take the video ID, that's in the item identifier, open ```~/.tubeup/.ytdlatchive``` in a text editor. Hit CTRL-F, find the line with ```zX7Q_8eobSU```. Delete everything below that line. 

Next, run ```rm ~/..tubeup/downloads/*```

Now re-run your rip. It should pick back up after the last successful upload.



Some tips:

- Don't use wifi to do the rips use wired ethernet, less collisions and lost packets. A much more stable connection is attained when doing this.
- Consider installing NSCD ```sudo apt install nscd```, it caches domain name lookups and closes off another avenue of errors.
- If running ethernet is infeasible, use a VPS.

**Comment by rudolphos** [comment]
@vxbinaca Will try adding video ID. 

Here's another problem I had:
- I tried to archive just one video by running "`tubeup videoid`" - which is a video that had been previously downloaded when I downloaded the whole channel, and the archive process didn't work.
- It didn't work.
- I removed that video id from `.ytdlarchive` and it still didn't work...


> "It sounds like a lot of videos on this channel are copyright blocked in certain countries"

I previously said that I also had the same problem when archiving different channel who has no copyright blocks.

I'm not using wifi. I'm using putty ssh which connects to a linux VPS in data center.

Next, run rm ~/.tubeup/downloads/*

It's 557 GB ... Isn't there any other way ? I don't have any bandwidth limit, but still it took a lot of time to DL all that..

I have also reinstalled all the components of tubeup and python. Sometimes it fixed some archiving problems, but not anymore.

**Comment by vxbinaca** [comment]
If you don't wipe the downloads, it will simply add them back to the archive file. It sucks but here's how I handle large channels ex: Healthy Addict.

Try printing video IDs using youtube-dl with the ```--get-id``` flag. The channels IDs will be in a handle list.

```youtube-dl --ignnore-config --get-id https://www.youtube.com/user/healthyaddict > target-IDs.txt```

(optionally you can use xargs to clean the output of youtube-dl to make the IDs in a list)

 Take the channel in chunks of 10 videos to start, if that runs well do 20 and do on. But with 557 gigs, holy shit are you sure Archive.org isn't throttling you? They have S3 limits.

A word on copyright takedowns:

```YouTube said: This video contains content from FranceTV mcn, who has blocked it on copyright grounds.``` This means you can't get the video in any region while ```blocked it in your country``` means 
you can use a VPS or VPN to get the video.

If the videos were subsequently blocked after you ripped them and still have them in the downloads folder....eh....better make an item for all the files and upload the entire directory using ```internetarchive```. But if you can re-rip the channel using tubeup, do that.

**Comment by rudolphos** [comment]
@vxbinaca 

> But with 557 gigs, holy shit are you sure Archive.org isn't throttling you?

So far so good, maybe they have changed the limits.. I've been archiving various stuff using tubeup since December 5th..

**Comment by rudolphos** [comment]
@vxbinaca I don't know how to do it, but the good way to check if it's been uploaded, would be to check if `https://archive.org/details/youtube-VIDEOID` exists and matches with the ID that's in `.ytdlarchive` file.

I guess one way would be to use excel to merge `.ytdlarchive` file lines with `archive.org` url and use website checker to see if page shows 404 error.

I am now manually checking those IDs by 100s on notepad++ adding bookmark and checking every 10th if it doesn't exist I add another bookmark and so on until I found ID that exists on archive.org.

All the bookmarked lines I remove after, this way I have reduced from 5 k to 2 k lines in .ytdlarchive..

**Comment by vxbinaca** [comment]
Just go to your user details page, look at the last successful upload that streams video, get it's video ID from the item identifier, find it in your archive file then just delete everything after that line.

It's janky but a quick way to make sure you don't re-upload things already up.

I've been doing 6 gig copies of live streams that are 8 hours long (1080p too) from YT to Archive. What in tarnation is 577 gigs out of curiosity?

Yeah leaving everything in your downloads folder just gets the videos re-added to the archive. It's a pain  in the ass but nothing like manually creating items.

**Comment by rudolphos** [comment]
>  last successful upload

It's not just one channel, it's like 7 channels and 3 soundcloud accounts..

And I have archived partly some channels successfully at the beginning, then something happened and nothing worked for a few days. I started archiving other channels after the ones who failed... My whole list is messed up, it's not just from one uploader, there are 140 IDS from uploader X1, 700 from uploader X2 and again uploader X1 and so on + soundcloud..

> What in tarnation is 577 gigs out of curiosity?
Various non-mainstream news videos with commentary + news segments. 2 k video podcasts, etc..

> Yeah leaving everything in your downloads folder just gets the videos re-added to the archive

That sucks.. Too bad there's no option to delete account with all items. I would want start again..

**Comment by rudolphos** [comment]
I was redownloading everything and trying to run archiving on channel in one batch, it wasn't successfull because error cancelled everything..

```
:: Upload Finished. Item information:
Title: aaaa
Upload URL: http://archive.org/details/youtube-aaaa
:: Uploading /root/.tubeup/downloads/aaa...
2016-12-19 00:39:51,374 - internetarchive.item - INFO - uploaded aaa-aaa.annotations.xml to https://s3.us.archive.org/youtube-aaa/aaa.annotations.xml
2016-12-19 00:39:51,374 - internetarchive.item - INFO - aaaa.annotations.xml successfully uploaded to https://archive.org/download/youtube-aaa/aaa.annotations.xml and verified, deleting local copy
2016-12-19 00:39:56,824 - internetarchive.item - INFO - uploaded aaa.info.json to https://s3.us.archive.org/youtube-aaa/aa.info.json
2016-12-19 00:39:56,825 - internetarchive.item - INFO - aa.info.json successfully uploaded to https://archive.org/download/youtube-aa/aaaa.info.json and verified, deleting local copy
2016-12-19 00:40:07,525 - internetarchive.item - ERROR -  error uploading aaa.f251.webm.part to youtube-aaa, Uploaded content is unacceptable. - video file has improper extension, try one of these: .webm
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 625, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Data for url: https://s3.us.archive.org/youtube-aaa/aaa.f251.webm.part

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 272, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 219, in upload_ia
    item.upload(vid_files, metadata=meta, retries=30000, request_kwargs=dict(timeout=30000), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 751, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 645, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading aaaa.f251.webm.part to youtube-aaaaa, Uploaded content is unacceptable. - video file has improper extension, try one of these: .webm
root@aaaa:~#

```

**Comment by vxbinaca** [comment]
You might want to read this: https://archive.org/help/derivatives.php

**Comment by rudolphos** [comment]
@vxbinaca Is there a way to skip .webm ? Because of this one problem I am unable to upload the rest of ~400 videos.. It just stops with .webm error

And it's weird that youtube-dl downloads videos as webms, it usually merges into mp4 or leaves default youtube mkv format..

**Comment by vxbinaca** [comment]
@rudolphos Problem downloading or uploading the webm? If the video stream only is webm, then the muxed format should be followed by deletion of the webm video-only stream. 

If the muxed video and audio are webm, then the uploads should work. I've uploaded in webm. Where is it failing?

**Comment by vxbinaca** [comment]
@rudolphos Did you resolve this? I have a solution (no code update) if you haven't come up with anything. Otherwise I'm closing.
