### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by JaffaCakes118** [bibanon/tubeup#313]
Since the new update, I get this error when trying to use tubeup:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\jaffacakes118\.local\bin\tubeup.exe\__main__.py", line 7, in <module>
TypeError: 'module' object is not callable

**Comment by vxbinaca** [comment]
I know and you didn't follow submission guidelines it's being cleaned up right now.

do this:

`pip3 install tubeup==2023.8.19` 

and wait for a new working version to be cut.

**Comment by vxbinaca** [comment]
I'm leaving this open so people know we know, until the Pypi packages can be cleansed.

**Comment by JaffaCakes118** [comment]
Sure thing.

**Comment by vxbinaca** [comment]
K it's fixed but I'm leaving this up for the next few weeks. All broken versions yanked.

**Comment by vxbinaca** [comment]
I think we can close this only a handful of people caught the bad version

**Comment by soredake** [comment]
After installing tubeup from git `pipx install git+https://github.com/bibanon/tubeup` I've got the same error.

**Comment by vxbinaca** [comment]
Follow submission guidelines don't necrobump
