### ISSUE TITLE
Bug report: `ModuleNotFoundError: No module named 'pkg_resources'` with python 3.12.1

### ISSUE THREAD

**Issue by soredake** [bibanon/tubeup#320]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [x] I understand Tubeup is merely a middleman between `yt-dlp` and `internetarchive`, and relies on said package dependiencies functioning properly, for example: Site extractors in `yt-dlp` become stale or sites change layout breaking regex, and `internetarchive` has outages or throttles users S-3 access, and that these things are beyond the control of the maintainers of Tubeup.
- [x] I've updated `tubeup`, `yt-dlp` and `internetarchive` along with their associated dependencies to their latest versions as supported by each afformentioned package setup scripts.
- [x] I've included the full and unredacted URL and console output (with the exception of site usernames and passwords, or IP addresses of the machine doing the download). I understand hiding URLs will get issue closed on sight.
- [x] I've checked that all provided URLs are alive, playable in a browser and arguments with special characters are properly quoted or escaped.
- [x] I've searched the issues (closed or open) for similar bug reports, not just here on Tubeup, but yt-dlps issue tracker for download issues similar to mine and internetarchives issue tracker for upload issues similar to mine. 
- [x] I'm not submitting a bug report about IA S3 timeouts (we have no control over Internet Archive outages or per-user throttling, and sometimes the site has maintence like hard disk swaps)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

yt-dlp version:
2023.12.30

`internetarchive` python client version:
3.6.0

Tubeup version:
2023.8.19

**Expected behavior**
Tubeup should work.

**Additional context**

**Comment by soredake** [comment]
https://github.com/jjjake/internetarchive/issues/613

**Comment by vxbinaca** [comment]
Closing because:

- This appears to be a 'internetarchive' problem
- There appears to be a solution in that issue you linked in the subsequent comment
- Your tubeup is horrifically out of date even though you checked the box
- You didn't provide a testable case, you running the tool on a URL and pasting the indented output here, demonstrating the failure which you checked the box for.

You just checked boxes. Closed.

**Comment by soredake** [comment]
> Your tubeup is horrifically out of date even though you checked the box

Horribly out of date? It's the latest version in this repo and on PyPI.

**Comment by vxbinaca** [comment]
You are correct I misread that apologies. Okay so edit the issue to include the video you're ripping and I'll test and figure out what went wrong. You've got 5 days to post the terminal output of the failed rip here or I close again.

**Comment by soredake** [comment]
That's probably IA fails, not tubeup:
```
❯ tubeup
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\tubeup.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\tubeup\Lib\site-packages\tubeup\__main__.py", line 60, in <module>
    import internetarchive.cli
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\tubeup\Lib\site-packages\internetarchive\cli\__init__.py", line 26, in <module>
    from internetarchive.cli import (
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\tubeup\Lib\site-packages\internetarchive\cli\ia.py", line 67, in <module>
    from pkg_resources import DistributionNotFound, iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by vxbinaca** [comment]
What URL is failing?
Have you installed `setuptools`?

**Comment by soredake** [comment]
> What URL is failing?

Just invoking `tubeup` gives me error.

> Have you installed `setuptools`?

After installing `setuptools` to both ia and tubeup venv's this error is gone, thanks.
