### ISSUE TITLE
option to choose quality/format or sending custom commands to yt-dlp

### ISSUE THREAD

**Issue by fenopa** [bibanon/tubeup#321]
I don't really want to waste the resources of the internet archive with full quality uploads, 720p or sometimes 480p would be more than enough for me with much smaller file sizes. Is there an option to choose the quality/resolution or change format option provided to yt-dlp ("-f" option) from tubeup? If not, it can be useful to add such an option.

**Comment by vxbinaca** [comment]
>well, sometimes it's a waste of resources. anyway I achived that by adding a "format" option to ydl_opts in TubeUp.py but it would be nice to have it as an option instead of modifying the TubeUp.py every time.

Jesus. Fucking. Christ. You're ruining history.

**Comment by vxbinaca** [comment]
>But they don't really have to be saved as 1080p60

Thats an editorial choice about the content you shouldn't be making. You are changing the result of what the site gave you for spurious reasons. 

>Also, wayback machine's own youtube archiver saves videos at maximum 720p quality anyway

Don't care we aren't IA or the Wayback.

>gobble-dee-guk about video formats

Don't care.

>so I don't think what I do is bad.

It is. You are bad for doing this. This isn't a fucking debate or something to be voted on. You're reducing the quality for a bullshit reason - not that any forced quality reduction could have a good reason. There is no good reason for what you are doing, you will annoy future users of the archive who cannot find better quality copies of a video that existed.
