### ISSUE TITLE
Fix: n-sig errors or double-video ripping in a item as of 07-09-2024

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#329]
Remove yt-dlp and tubeup with pip, pipx or your distros package manager:

```
sudo apt remove yt-dlp ; pip3 uninstall yt-dlp tubeup  ; pipx uninstall yt-dlp --force ; pipx uninstall tubeup --force
```

Install pipx.

Re-install tubeup with pipx, but include the dependencies inside the venv for tubeup, and this time you're injecting the latest nightly for yt-dlp:

**You will need to look up what the latest yt-dlp nightly is, and not just blindly copy and paste this command into your terminal.**

**You will need to replace ```2024.07.09.232843``` with whatever the latest nightly that has a youtube/site extractor fix you need.**

```
pipx install tubeup --include-deps  ;  pipx inject tubeup "yt-dlp[default] @ https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.09.232843/yt-dlp.tar.gz" --force
```

Ensure the path for pipx:

```
pipx ensurepath
```

Give it a spin.

**Comment by mrpapersonic** [comment]
Dunno if this is still relevant but pinning it so it's easier to users to find a fix
