### ISSUE TITLE
FIX: Tubeup broken after internetarchive 5.0.0

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#338]
Remove Tubeup using pipx (if you installed it with pipx), and remove `internetarchive`

Then run:

```
   pipx install yt-dlp[default]
   pipx install tubeup
   pipx inject tubeup internetarchive==4.1.0
```

This should get you back up and running until Tubeup gets a proper fix.

**Comment by mrpapersonic** [comment]
> @mrpapersonic
> 
> Don't ever commit code to this repository you didn't test.
> 
> ```
> Traceback (most recent call last):
>   File "/home/vxbinaca/.local/bin/tubeup", line 5, in <module>
>     from tubeup.__main__ import main
>   File "/home/vxbinaca/.local/share/pipx/venvs/tubeup/lib/python3.12/site-packages/tubeup/__main__.py", line 59, in <module>
>     from utils import key_value_to_dict
> ModuleNotFoundError: No module named 'utils'
> ```
> 
> I will require before comitting:
> 
>     * full command and full console output INDENTED
> 
>     * test item up on IA linked in commit
> 
> 
> Hard reversion incoming

I fixed this locally but for some reason git didn't add it onto the commit...

**Comment by Windows81** [comment]
I'm making changes, but the Internet Archive Python library has bugs.

`__main.py`
```patch
- metadata = internetarchive.cli.argparser.get_args_dict(args['--metadata'])
+ metadata = internetarchive.cli.cli_utils.get_args_dict(args['--metadata'])
```

I've made [a pull request over there](https://github.com/jjjake/internetarchive/pull/662) and have tested it along with the above changes I suggested.

**Comment by elgato9857** [comment]
> Okay it's still broken after 5.0.3.
> 
> I'm cutting a new version that locks the dep for `internetarchive` at 4.1.0, removing python 3.8 support, and calling it a day until someone wants to tackle this and show their changes work with test items. I'm not a programmer I'm a tradesman, however I know how this program should function and I suspect it's why I'm kept around because it's not charm or looks.
> 
> Please include with any PR:
> 
> * Full command and terminal output indented in PR.
> * Link to test item ripped using your changes PR to show to me that the code is sane and works.
> * Bonus: commit to each file with a explanation to which you'd give a child each commit you're doing.
> 
> Thank you ladies and gentlemen, have a wonderful day.

This seems to be the most recent update for this issue. Many of us are hobbies archives, and not very familiar with Lennox in general. Can you provide the appropriate commands for us to run to completely remove the application and all of its dependencies and then reinstall it with the correct (working) most recent version. The current version that I have was working great until the Internet archive got hacked, and now they seem to have recovered from the hack, but tubeup will not upload anything.
