### ISSUE TITLE
Add Support for Wenoo (wenoo.net)

### ISSUE THREAD

**Issue by dkl3** [bibanon/tubeup#34]
Gives this output when I try and reupload a video from wenoo.net:

BLANK@BLANK-550P5C-550P7C:~⟫ tubeup http://wenoo.net/video/4d2de9a85124dc64613
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.5.2 - Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 2601:600:9201:8030:4c3:a3e3:c362:986c
{'_total_bytes_str': '7.59MiB', 'status': 'finished', 'filename': '/home/BLANK/.tubeup/downloads/Puyo_Puyo_Tetris_-_Official_Nintendo_Switch_Trailer-4d2de9a85124dc64613.mp4', 'total_bytes': 7958264, 'elapsed': 3.245335578918457, '_elapsed_str': '00:03', 'downloaded_bytes': 7958264}
:: Downloaded: /home/BLANK/.tubeup/downloads/Puyo_Puyo_Tetris_-_Official_Nintendo_Switch_Trailer-4d2de9a85124dc64613.mp4...
:: Uploading /home/BLANK/.tubeup/downloads/Puyo_Puyo_Tetris_-_Official_Nintendo_Switch_Trailer-4d2de9a85124dc64613...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 9, in <module>
    load_entry_point('tubeup==0.0.4', 'console_scripts', 'tubeup')()
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 272, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 161, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
KeyError: 'upload_date'

**Comment by vxbinaca** [comment]
The reason this is happening is because the video site isn't providing a date the video was uploaded, so on upload it chokes. This is a known issue and as I'm not a programmer I can't do anything about it. Facebook is another site it does this with.

**Comment by antonizoon** [comment]
I mean can't we just catch the KeyError exception for each item? I do this multiple times in the code.

**Comment by antonizoon** [comment]
In __main__.py it should be catching a KeyError, not a ValueError. I don't know why we were looking for that exception.

**Comment by antonizoon** [comment]
Fixed in 0.0.5.
