### ISSUE TITLE
Script fails an entire channel upload if one video has already been uploaded by someone else.

### ISSUE THREAD

**Issue by wertercatt** [bibanon/tubeup#36]
I attempted to use tubeup to automatically repost the 4,400 videos that https://www.youtube.com/channel/UC5VlSHEz9tXpli-iPEb5m5g has made, which consist of old advertisements and show bumpers which could be lost otherwise. Unfortunately, it quickly failed and died because someone else had already uploaded a single video from the channel and it didn't handle the error at all. The item that caused the error was http://archive.org/details/youtube-GjqajlJjhz4/, which was uploaded by DKL3. It needs to be able to resume uploads of a channel if a video has already been done.

**Comment by wertercatt** [comment]
Here's the part of the log with the error.
`2017-05-26 07:11:29,388 - internetarchive.item - INFO - 100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.jpg already exists: https://s3.us.archive.org/youtube-GjqajlJjhz4/100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.jpg
2017-05-26 07:11:29,388 - internetarchive.item - INFO - 100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.jpg successfully uploaded to https://archive.org/download/youtube-GjqajlJjhz4/100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.jpg and verified, deleting local copy
2017-05-26 07:11:31,863 - internetarchive.item - ERROR -  error uploading 100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.annotations.xml to youtube-GjqajlJjhz4, Access Denied - You lack sufficient privileges to write to this item.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 645, in upload_file
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us.archive.org/youtube-GjqajlJjhz4/100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.annotations.xml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 208, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 771, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 665, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading 100_Deeds_for_Eddie_McDowd_Movie_Promo_2000_Incomplete-GjqajlJjhz4.annotations.xml to youtube-GjqajlJjhz4, Access Denied - You lack sufficient privileges to write to this item.

`

**Comment by vxbinaca** [comment]
Yeah DKL3 and Rudolphos are notorious for fucking up my rips by doing a few videos from the subject I want to do. It's okay though it's east to fix.



Install vim.

Remove the contents of your tubeup cache folder:

```rm ~/.tubeup/downloads/*```

Then let's carve around the problem item:

```cat ./tubeup/.ytdlarchive | grep -n GjqajlJjhz4```

The output will give you a line number, the first character on that line are the line number. Remember that number.

```vim ~/.tubeup/.ytdoarchive```

Type that number, then hit Shift-G.

While in command mode, not editing mode, type ```jdG``` (Remember to Shift-G). This will erase everything below that line.

Make sure the line that says ```youtube GjqajlJjhz4```remains so you don't run into this problem again.

Then exit and save by typing ```qw```

Re-run your rip. Rinse and repeat for every problem item. Consider researching what from that channel is already up and pre-loading those items into your archive file to avoid problems.

I'm going to give you 5 days to respond either way, or I'm closing the issue.

**Comment by vxbinaca** [comment]
@wertercatt  You'd be wise to email Arvhive.org staff, either @jjjake  or Jeff Kaplan, to let them know you're doing a huge dump like that. Otherwise they'll shut you off like happened to me. Be sure to create a collection for those items.

**Comment by wertercatt** [comment]
Alright, thanks for the help vxbinaca.

**Comment by vxbinaca** [comment]
Closing because this isn't a bug.

**Comment by vxbinaca** [comment]
@wertercatt actually I'm still getting the hang of Vim, so you can open Vim and in command mode, type /[STRING] - with [STRING] being the VideoID, and it will jump to that line. Follow the directions otherwise but simply shaving time off your efforts.
