### ISSUE TITLE
Requires manually installing version 0.4 of jsonpatch

### ISSUE THREAD

**Issue by omgitsraven** [bibanon/tubeup#39]
I just followed the installation instructions on OS X, and got an error when I tried running tubeup that seems to have amounted to it expecting strictly version 0.4 of jsonpatch. I uninstalled jsonpatch and reinstalled it as 0.4 and... well, it moved on to a different error, but that's a matter for another thread...

Interestingly, it seems like it had originally installed jsonpatch 0.4 in the first place, but updated it to 1.16 when I ran the "periodically upgrade tubeup and its dependencies" line, so if the requirement isn't going to change, it might be worth taking jsonpatch out of the list of things to update in that line.

**Comment by vxbinaca** [comment]
First, output please.

Second: There is a known bug in `internetarchive-1.6.0` where our script specifies a timeout and theres a hard coded timeout and they conflict.

Downgrade internetarchive to 1.5.0

`pip3 install -U internetarchive==1.5.0`

Please try again and report back here, preferably with command line output this time.

**Comment by vxbinaca** [comment]
We don't actually require jsonpatch 0.4 that's another package, that package and version is a req of `internetarchive` though.

You need to go to @jjjake and open an issue with `'internetarchive'.

Closing due to it not being our bug (but we do have one, just not this one).

**Comment by omgitsraven** [comment]
I'm not sure what to report to `internetarchive`, as I don't know how to reproduce this problem other than by using tubeup. Can you give me an example of some other usage that would trigger it, based on the error log?

```
Andrews-MacBook-Air:~ andrew$ tubeup https://www.youtube.com/watch?v=VqnFy04KctI
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonpatch 1.16 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages), Requirement.parse('jsonpatch==0.4'), {'internetarchive'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tubeup", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonpatch==0.4' distribution was not found and is required by internetarchive
```

**Comment by vxbinaca** [comment]
Why not force install jsonpatch 0.4:

`pip3 install -U jsonpatch==0.4`

How up to date is the rest of your install? Is the output the first or second time you tried running it?

It may take some time time for Jake to respond as he's actual staff and I'm an amateur (but not slouch at 50k videos saved)

**Comment by omgitsraven** [comment]
I did force install jsonpatch 0.4 just like that, and that fixed the problem. I just mentioned it here for the sake of anyone else having the same issue, and so the readme could be adjusted to avoid it for other people in the future.

Roughly what happened was:
- I installed everything
- I updated everything
- I tried running it, and got the log you see above
- I force installed jsonpatch 0.4
- I got a different error, related to the timeout bug
- I force installed internet archive 1.5.0
- Everything works now.

I tried updating and rolling back to 0.4 a few times just to ensure that that was the issue a few times, but I forget exactly when by now. So yes, I'm fine, I've gotten a video archived successfully at this point. Just thought I'd mention the one issue I ran into while trying to follow the instructions in the readme. (Well, other than the timeout bug which I know you're already aware of.)

**Comment by vxbinaca** [comment]
Okay, great I'll let Jake know because I agree, I think it's odd to reply on such an old version.

**Comment by jjjake** [comment]
`internetarchive` was locked in at `jsonpatch` 0.4 because the metadata API was dependent on an earlier version of the JSON Patch standard. I am pretty certain that is no longer the case.

I went ahead and loosened the requirements: https://github.com/jjjake/internetarchive/commit/f4a275e4efa760cd66ebeecd8564703c9226488c

If others are able to test `ia upload` and `ia metadata <id> -m key:val` works as expected with more recent versions of `jsonpatch`, that would be helpful.

I'll do some more testing myself next week. If everything looks good, I'll go ahead and ship a new version (I know you're still waiting on the upload timeout bugfix to be shipped).

**Comment by vxbinaca** [comment]
I'll work on testing it this weekend. I'm testing metadats changes to tubeup right now.
