### ISSUE TITLE
Upload URL should use https

### ISSUE THREAD

**Issue by rchrd2** [bibanon/tubeup#42]
Please change

```
Upload URL: http://archive.org/details/youtube-xxxxxxxx
```
to
```
Upload URL: https://archive.org/details/youtube-xxxxxxxx
```

**Comment by vxbinaca** [comment]
Can you provide a link to an item that has http and not https?

**Comment by rchrd2** [comment]
All items have https, so that is why i'm suggesting the URL that is outputted be changed to https.

Here's an example: https://archive.org/details/youtube-Qgtoib4q0k0

**Comment by rchrd2** [comment]
Thank you!

**Comment by vxbinaca** [comment]
No problem.

I've torn apart the opts in this script, I honestly don't have an explanation for why I didn't notice this. I usually didn't go this far down into the script.

**Comment by vxbinaca** [comment]
@rchrd2 Sorry for the zombie-posting here, but Archive.org 302 redirects you to HTTPS, so this wasn't necessary other than for aesthetics.

**Comment by rchrd2** [comment]
I believe, it's still preferable to go to HTTPS directly, because if you do an HTTP request first, you have already transferred some data in the clear (eg cookies).

**Comment by vxbinaca** [comment]
Have you verified that with a packet capture? Asking out of genuine curiosity.
