### ISSUE TITLE
Archive.org - So many items are 'not found'

### ISSUE THREAD

**Issue by rudolphos** [bibanon/tubeup#49]
I've noticed so many videos I randomly click on are not found.

> The item you have requested had an error:
> Item cannot be found.
> which prevents us from displaying this page.
> 
> If you would like to report this problem as an error report, you may do so here.

For example some random Japanese video, IDK what that even is, but it was mirrored from niconico.

![image](https://user-images.githubusercontent.com/4366810/31587471-0014b21c-b1eb-11e7-8336-caf52c1fbad2.png)

https://archive.org/details/niconico-sm26635762

I clicked on many - 90% Molyneux videos in the screenshots and they are all 'not found'.
![image](https://user-images.githubusercontent.com/4366810/31587514-b97725fa-b1eb-11e7-8b19-80d5bcb65e38.png)

Also many videos of Jordan B. Peterson are gone.

But the fact is that so much of what I have uploaded and many others are lost. Is this archive.org internal problem or they remove items on purpose now (because of tags..)?

They seem to be digging their own grave.

![image](https://user-images.githubusercontent.com/4366810/31587526-f892ba1a-b1eb-11e7-93e5-2983cff92814.png)

**Comment by vxbinaca** [comment]
Email staff and ask why you were banned. Work with them on returning. 

Not this is purely technical what's happening. I've had vidoes go in and out of being broken. They recently implemented a new item layout. So no it's not intentional. 

Closing because this isn't our problem.

**Comment by vxbinaca** [comment]
@rudolphos Sometimes drives die and items on them will go dark, so until the drives are replaced things may be wonky for up to 8 hours or so.

[Here are my items from Jordan Peterson](https://archive.org/search.php?query=creator%3A%22Jordan+B+Peterson%22) and they're still up.

**Comment by rudolphos** [comment]
>Sometimes drives die and items on them will go dark, so until the drives are replaced things may be wonky for up to 8 hours or so.

You might be right.

@vxbinaca  Very weird.  I revisited those links that yesterday were showing as not found and today they are all working.

**Comment by vxbinaca** [comment]
@rudolphos in the future please both follow IA on Twitter and wait 24 hours before asking us.

This would have been quickly not needed if you'd read this : https://twitter.com/internetarchive/status/919957880568102912
