### ISSUE TITLE
Can't re-upload if upload fails while it's in progress

### ISSUE THREAD

**Issue by hook54321a** [bibanon/tubeup#60]
If uploading fails then it's not possible to simply redo the same command to reupload everything, since the item already exists.

**Comment by vxbinaca** [comment]
- Remove the entry from the `.ytdlarchive` file
- `rm ~/.tubeup/downloads/*`
- Re-run the rip.

**Comment by 111100001** [comment]
i'm having this issue rn

**Comment by vxbinaca** [comment]
Please make a new issue and follow the issue submission guidelines.

> i'm having this issue rn
> 
> couldn't find the .ytdlarchive file anywhere

Please make a new issue and follow the issue submission guidelines.
