### ISSUE TITLE
When grabbing from vid.me, video category isn't in a topic or info.json

### ISSUE THREAD

**Issue by hook54321a** [bibanon/tubeup#62]
The video category isn't in a topic or in info.json on archive.org

Example video:
https://archive.org/details/vidme-vKd8h
https://vid.me/vKd8h

**Comment by vxbinaca** [comment]
I'm looking at the topic for the item you supplied and it says "video"

So this isn't our problem, here's why: This is youtube-dl's problem. We only work with what youtube-dl and the video sites give us. Talk to youtube-dl, open an issue and ask them.

But perhaps I'm missing something. Elaborate before I decide what to do with this issue.
