### ISSUE TITLE
Suggestion: Option to archive geo-blocked video/channel (youtube-dl feature)

### ISSUE THREAD

**Issue by rudolphos** [bibanon/tubeup#64]
Currently when trying to archive a channel it shows

`ERROR: Youtube said: This channel is not available in your country.`

But yt-dl has an option to bypass this:

https://github.com/rg3/youtube-dl#geo-restriction

```
--geo-bypass  Bypass geographic restriction via faking X-Forwarded-For HTTP header (experimental)
```

Would be a good addition to this script if we could add this flag at the end or somewhere when launching tubeup command, because for me proxies rarely work, so I had used VPNs in the past to bypass yt geo-censorship.

**Comment by vxbinaca** [comment]
I've already experimented with the bypass feature and it doesn't work for replacing a VPS, which is what we use to bypass geo-blocking. 

Closing because it's not a problem with tubeup.
