### ISSUE TITLE
Flickr uploader info

### ISSUE THREAD

**Issue by emijrp** [bibanon/tubeup#71]
Sometimes the info.json file doesn't have a value for "uploader", and it is left in blank on IA https://archive.org/details/Flickr-23515915275

In Flickr cases, it happens when usernames in URLs are like this "27718315@N02" https://www.flickr.com/photos/27718315@N02/23515915275/

A quick solution could be to use "uploader_url" value as "uploader". This way, on IA we will see:

* Uploader: https://www.flickr.com/photos/27718315@N02/

**Comment by vxbinaca** [comment]
That's messy because each item would not be sortable by creator. Were dealing with a not-to-dissimilar problem with #68 though. Perhaps they're related? We hypothesize Youtube-dl is dropping the ball somewhere on the JSON metadata.

**Comment by vxbinaca** [comment]
Also this was merged.This seems to be a Flickr specific issue. Perhaps contact Youtube-dl guys about fixing their extractor?
