### ISSUE TITLE
Define upload URL

### ISSUE THREAD

**Issue by Coool** [bibanon/tubeup#80]
Is it possible to change default YouTube upload url
https://archive.org/details/youtube-iii
to
https://archive.org/details/youtube-iii-kkk

Sometimes uploading videos you have "Access Denied - This item has been taken offline" error, when archive.org team remove some video on user request or violation use terms. You can't upload video under same url. Maybe add command line option to specified upload url.

Thanks.

**Comment by vxbinaca** [comment]
No. We don't want duplicate uploads.

**Comment by DuckHP** [comment]
> Is it possible to change default YouTube upload url
> https://archive.org/details/youtube-iii
> to
> https://archive.org/details/youtube-iii-kkk
> 
> Sometimes uploading videos you have "Access Denied - This item has been taken offline" error, when archive.org team remove some video on user request or violation use terms. You can't upload video under same url. Maybe add command line option to specified upload url.
> 
> Thanks.

I really don't see the issue. If it violated the terms of use, it would make more sense to contact IA to e.g appeal such a decision on their [forum](https://archive.org/iathreads/forums.php) . Anything else, _especially_ trying to re-upload material that's already been deemed in violation of terms,  would make absolutely no sense at all.

I'm not sure what you mean by 'remove some video on user request'  or imagine the type of content, but keep in mind that illegal content is a matter of [law encforcment take-down requests](https://help.archive.org/hc/en-us/articles/360004716011-Law-Enforcement-Requests)

**Comment by brandongalbraith** [comment]
Agree with @DuckHP; if the Internet Archive has darked or blacklisted an
item, DO NOT attempt to reupload with modified metadata. Keep a copy in
your local storage system instead.

**Comment by antonizoon** [comment]
You're unfortunately going to have to understand that YouTube , 4chan, Google Drive, Dropbox, and the Internet Archive all operate under the same jurisdiction under the laws of the State of California, so the majority of content taken down will be ordered to be removed again by lawyers or federal agencies if reuploaded to such services. 

The fact that this content was overlooked in the past is no excuse in the eyes of lawyers and legislators. Continual flouting of state and federal copyright law poses an existential threat to the continued operation of the internet archive, as you saw with YouTube they were forced by Viacom to take affirmative action with imperfect AI to ensure that copyrighted content is blocked.

And although some of us may like to stick it to the man none of us really have the right to tell them what to do with their service, in the US property rights trump even free speech on private property. We have no stake in their hard drive and no right to try and force it in there. The flip side of this is, for the vast majority of content you are not in violation of any laws and statutes if you keep the videos and do not share them. Therefore, a good strategy is to upload them to an unlimited Google Drive account encrypted with rclone for future release in some other jurisdiction, or to find servers outside of this jurisdiction (perhaps in places that have bigger problems than enforcing Hollywood copy wrong) and seed this content from there on torrents or IPFS. (Beware that if no one is contributing resources to seed the file even on IPFS will be as dead as a dead torrent) You have to take it upon yourself to host this data with your own resources and capital if you wish to keep the content around.

**Comment by Coool** [comment]
> 
> ...
> 
> I'm not sure what you mean by 'remove some video on user request' , and can't imagine the type of content, **but** keep in mind that illegal content might be a matter of [law enforcement take-down requests](https://help.archive.org/hc/en-us/articles/360004716011-Law-Enforcement-Requests) , and not simply 'user requests'. So keep in mind, Internet Archive is subject to US law, for better or worse, and which may differ from laws in other countries.
> 
> ...

Issue was what I uploaded some items under different username and wanted to reupload with new username. So I asked archive,org stuff to remove some videos. But you can't reupload them under same id. Anyway I will add them manually.
