### ISSUE TITLE
Suggestion: Reverting to a (local) list of proxies upon geoblocked videos

### ISSUE THREAD

**Issue by DuckHP** [bibanon/tubeup#83]
Problem: When trying to download certain youtube playlists by using the playlist link, the download (and the upload) process will sometimes fail critically with `"<some party> has blocked this video in your country"` . From what it seems like, this is usually a case of when the video uploader have had his or her video monetized/claimed by some other third party trough _ContentID_detection (legitimate or not).

Suggestion: Instead of completely failing/aborting the entire task of the playlist _(which also stops it from uploading the other successfully downloaded videos in the list)_
1. Auto-iterate trough, for that specific video., **if exist**, a local list of proxies (e.g `~/.tubeup/proxies`) where each line contain `proxyip:proxyport` and/or `user:pass@proxyip:proxyport` . _[And perhaps with a simple template file having a comment header explaining ip:port line format and that it needs to be a list of one or more **[non-transparent proxies](https://networkengineer.me/2014/04/28/transparent-proxy-vs-non-transparent-porxy/)** etc.]_. 
_- Being able to supply `--proxy` argument with a comma separated list (e.g `--proxy '127.0.0.1:81,myusrname:mypass@domain.cxm:4848'`) , instead of just one address, might do just as well as an alternative. Perhaps especially in situations where Docker is utilized for tupeup tasks, since an ENV variable could be then used to set to a list of proxies_

2. If still unsuccessful download trough proxies, skip that specific video and log it to a local list (e.g `~/.tubeup/failed` and/or `~/.tubeup/failed_geo`), similar when using `--use-download-archive` , for manual resolving/retry and/or export. Then automatically move on to (try) the next video in the playlist.

**Comment by antonizoon** [comment]
Probably a good idea to deal with this annoying issue, but that's up to youtube-dl to fix upstream. Look for a comparable issue opened there?

**Comment by DuckHP** [comment]
> Probably a good idea to deal with this annoying issue, but other than adding a proxy option, skipping geolocated videos is up to youtube-dl to fix upstream. Look for a comparable issue opened there? Or maybe they have an argument to skip such videos?

I see it's got `--ignore-errors ` and apparently some [geo-restrictions workarounds](https://github.com/rg3/youtube-dl#geo-restriction) _(never personally tried those)_

Though, would those work with tubeup's `--use-download-archive` ?

**Comment by DuckHP** [comment]
I've just now come across this previous issue being here https://github.com/bibanon/tubeup/issues/64

**Comment by vxbinaca** [comment]
- Geo-block bypass is experimental and didn't work in my testing. Use a VPS. You're gonna have to spend money somehow or get access to a box in another country to bypass. Baking it in would break ripping in other countries where it would have normally worked. It's a command with no demonstrated usefulness to us that risks breaking rips for most users. No.

- `--ignore-errors` is so it doesn't seize on a entire playlist or channel. This flag pre-dates my touching the code. It stays.

- `--use-download-archive` is used by a tiny number of people to maintain rips. It's turned off by default. Turning it on makes it so you don't re-rip other videos you've already downloaded. It used to be on by default but caused problems so @refeed originally had removed it but I insisted it go back in but as a flag, which was what should have been done in the first place.

We're accepting pull requests so if you can get something working for proxies we'll take a look.

**Comment by vxbinaca** [comment]
The most reliable way to bypass geoblocks is a VPS/VPN. 

I'm not inherently opposed to adding proxy functionality as we can call YouTube-dl to do it with a flag instead of a hacky fix on our end.

Also I sense you could benefit from a better understanding of how to best get the most success in ripping hence I'm not yet closing this issue. Ask away.

**Comment by brandongalbraith** [comment]
I want to echo @vxbinaca here; it is highly preferable to run tubeup and youtube-dl from VPS instances or other compute points where the networking is highly likely to be clean (no MITM, no DNS mods by the service provider), not blocked by geo, etc. That doesn't mean a fix can't be implemented to pass through the necessary args to youtube-dl, BUT using proxies should be a failure mode of last resort.

**Comment by vxbinaca** [comment]
Brandon has a point about DNS mods. My home machines use iPredators public resolvers and it's hard coded into everything. Ontop of that I use NSCD to cache results so every packet isn't being looked up. This greatly smooths rips and reduces the chance of failure. The VPS is exposed directly to the internet.

Torrenting and privacy VPNs also monkey with cookies, IE blocking them. Great for privacy but not for our uses.

**Comment by vxbinaca** [comment]
Google hasn't banned us but, if they do since we use a VPS we can ask to be moved to a new pool or just just switch services. Proxying is a desperate last step.

But I'll leave this open so conducive discussion can can happen.

**Comment by vxbinaca** [comment]
@brandongalbraith We should put this in the wiki and there should be a recommended setup for machines.

I'm leaving this issue open for a few weeks if anyone has any related networking questions.

Happy new year everyone!
