### ISSUE TITLE
Archive YouTube videos -xyxyxy

### ISSUE THREAD

**Issue by Coool** [bibanon/tubeup#84]
How to archive YouTube videos which starts with -xyxyxy? Getting tubeup usage help in output. All works fine if using https://youtu.be/-xyxyxy as URL.

**Comment by vxbinaca** [comment]
Having tubeup do the general search through youtube-dl is dangerous because in all likely hood you'll rip the wrong thing. Do the search yourself through youtube-dl separately and then save those URLs, then rip them that way. 

Are you searching in a channel or on the site generally?

**Comment by vxbinaca** [comment]
Oh VideoIDs that start with a dash are being recognized as a flag when they aren't. Just use the full URL in that case.

**Comment by Coool** [comment]
I already figure out by myself. 

Thanks. :+1:

**Comment by DuckHP** [comment]
adding " or ' to an url should help . This goes for any links containting & as well i guess .

**Comment by vxbinaca** [comment]
Thanks Duck, but youtube-dl will trim off that excess.
