### ISSUE TITLE
Feature request: Attempt to fix malformed video/audio, or option to force re-encode/container

### ISSUE THREAD

**Issue by DuckHP** [bibanon/tubeup#85]
A couple of days ago, i did tubeup'ed a few tweets by a journalist containing video. But, when i fortunately happened to check in on one of the items, i noticed the audio was playing back garbled/sped up _(in Chromium)_ . I then checked the other ~5 items and saw that the same issue was present there.

However, i then checked the derived OGV files, and they played back just fine. I figured i would then check to see if the items played back in a different browser _(Waterfox/Firefox)_ only to find out that in Firefox based browser(s), apparently neither video or audio will play back at all on [the IA items](https://archive.org/details/@duckhuntpr0?and%5B%5D=creator%3ASotiri+Dimpinoudis&sort=-publicdate&and%5B%5D=mediatype%3A%22movies%22&and%5B%5D=year%3A%222019%22).
_(confirmed with the help of @JustAnotherArchivist )_

When trying to re-do the items with a rebuilt version of ffmpeg _(thinking it might've been ffmpeg bug etc. on my end)_ , today i noticed it says in terminal:
> 1086563329575976961: malformed AAC bitstream detected.

before the IA uploading step began. When running 

> tubeup https://twitter.com/sotiridi/status/1086563329575976961

So, since the derived OGV play back just fine on IA _(who uses ffmpeg to derive i believe)_, would it be possible to request having tubeup fix such (minor?) problems locally, before an IA upload step? Or have it as an option to force a re-encode/container-(re)format during tubeup's ?

I can imagine that it might cause quite a few "Flagged as broken" reporting at IA, from users who try to play items with the same or similar problems, only to either get garbled sound or the IA player showing Error in their browser.

( one of the items in question: https://archive.org/details/twitter-card-1086563329575976961 )

ffmpeg version 4.1 (https://aur.archlinux.org/packages/ffmpeg-full/)
youtube-dl version 2019.01.17

**Comment by vxbinaca** [comment]
MIME type issue with browser makers not us. If it derives 'correctly' then it was sent correctly. Either that or IA needs to update on their site what cam be streamed which also isn't us.

Closing because we can't fix this.

**Comment by DuckHP** [comment]
Fair enough. I'm then thinking @internetarchive might be where it falls on then, since both @google or @mozilla would probably take milennias to bother fixing it :rofl:

**Comment by vxbinaca** [comment]
It's not really a major issue because the video is preserved. You just can't play it in Linux built browsers yet. It's also something we can't fix.

By the way, since I see you're ola_norsk: Please refrain from ripping Sargon of Akkad I have scripts trained on his channel and they'll get his videos automatically. I have it taken care of.

**Comment by vxbinaca** [comment]
re: forcing container re-encodes:

- No because that would choke a VPS box
- No because we let youtube-dl pick the best audio and video
- No because we take what youttube-dl gives us and not mess with it too much.

**Comment by DuckHP** [comment]
> By the way, since I see you're ola_norsk: Please refrain from ripping Sargon of Akkad I have scripts trained on his channel and they'll get his videos automatically. I have it taken care of.

Duly noted! :ok:
