### ISSUE TITLE
Extraction error occured when downloading a video that has been copyright blocked.

### ISSUE THREAD

**Issue by NDokeh** [bibanon/tubeup#86]
the command was as follows: 

tubeup https://www.youtube.com/user/DigibronyMLP/videos

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/tubeup/main.py", line 91, in main
>     use_download_archive):
>   File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 356, in archive_urls
>     urls, proxy, ydl_username, ydl_password, use_download_archive)
>   File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
>     self.create_basenames_from_ydl_info_dict(ydl, info_dict)
>   File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
>     filenames.add(ydl.prepare_filename(video))
>   File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 633, in prepare_filename
>     template_dict = dict(info_dict)
> TypeError: 'NoneType' object is not iterable

After this error, tubeup stops running. I've tried running the same url again:

And this what caused the error: youtube_dl.utils.ExtractorError: This video contains content from Molebeat, who has blocked it on copyright grounds.

**Comment by vxbinaca** [comment]
1) please use this tracker in the future. You've seen the issue tracker and didn't use it.
2) edit your issue with the command you used. Do not censor or obscure any information.

**Comment by brandongalbraith** [comment]
Please provide the video URL for troubleshooting purposes.

**Comment by NDokeh** [comment]
@vxbinaca @brandongalbraith 

 https://www.youtube.com/user/DigibronyMLP/videos

**Comment by vxbinaca** [comment]
Print the video IDs (--get-id) with youube-dl and rip the videos one by one inna batch file. If you need VIM tips on how to do this ask.

**Comment by NDokeh** [comment]
Batch file? I've never done this before

**Comment by NDokeh** [comment]
Also here's what caused the error: And this what caused the error: youtube_dl.utils.ExtractorError: This video contains content from Molebeat, who has blocked it on copyright grounds.

**Comment by vxbinaca** [comment]
1) think hard about what you dump onto IA and if it's really in danger of vanishing.

2) I'll make a list of commands for you to run in a few hours, paste them here in a patebin and then close the issue.

**Comment by vxbinaca** [comment]
Yeah that's a copyright strike. Tubeup should move past that

**Comment by NDokeh** [comment]
@vxbinaca Here's another error that popped up as well when archiving rokcp1303

tubeup https://www.youtube.com/user/rokcp1303/videos

Downloaded /home/jkid/.tubeup/downloads/Attack_on_City_Hall_Police_VS_Protesters-7qsdvTaFskc.f251.webm

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/lib/python3.4/site-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 633, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable

**Comment by vxbinaca** [comment]
One of the videos was erroring for:

`
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
`
Or embedding disabled.  I don't think you can even disable that anymore I have not seen this done in like 10 years.

So here's what I'm going to do for you and only you this one time and never again: I'm going to rip this channel for you since it's tiny.

Now, this channel has been up for 13 years. It has videos on it. Is it in danger? Can you articulate why it is at risk of being removed? I'm going to lean to no it's not in danger 

Think before you rip. The Internet Archive are a non-profit.
