### ISSUE TITLE
YouTube video-id begining with '-' is uploaded to Internet Archive without the '-'

### ISSUE THREAD

**Issue by altCensored** [bibanon/tubeup#88]
many thanks to everyone who has made tubeup and the Internet Archive possible.

i uploaded a YT video that begins with a '-' :
$ tubeup https://www.youtube.com/watch?v=-QBwhSklJks

it appears at IA without the dash:
https://archive.org/details/youtube-QBwhSklJks

i changed file TubeUp.py at line 280 from:
itemname = re.sub('\W+', '-', itemname)
to:
itemname = re.sub('[^a-zA-Z0-9-]+', '-', itemname)
and was able to run the same command and upload to IA with the same video-id as YT:
https://archive.org/details/youtube--QBwhSklJks

i have seen other items on IA with the same YT video-id (https://archive.org/details/youtube---nIlPrkYmA) but am sending an email to the Internet Archive for clarification.

**Comment by altCensored** [comment]
many thanks to everyone who has made tubeup and the Internet Archive possible.

i uploaded a YT video that begins with a '-' : 
$ tubeup https://www.youtube.com/watch?v=-QBwhSklJks

it appears at IA without the dash:
https://archive.org/details/youtube-QBwhSklJks

i changed file TubeUp.py at line 280 from:
itemname = re.sub('\W+', '-', itemname)
to:
itemname = re.sub('[^a-zA-Z0-9-]+', '-', itemname)
and was able to run the same command and upload to IA with the same video-id as YT:
https://archive.org/details/youtube--QBwhSklJks

i have seen other items on IA with the same YT video-id (https://archive.org/details/youtube---nIlPrkYmA) but am sending an email to the Internet Archive for clarification.

**Comment by vxbinaca** [comment]
I'd appreciate a pull request for the fix. Thanks. This is our bug not theirs.

**Comment by vxbinaca** [comment]
Again. Thank you for spotting this.

**Comment by altCensored** [comment]
ok, i forked tubeup, made the change to a branch there, then created a pull request here.
it's my first time doing a pull request, hope it is right!

**Comment by altCensored** [comment]
this is not ready, do not use.

NUFX_eC84SE was changed to NUFX-eC84SE.

am looking further ...

**Comment by altCensored** [comment]
is a regex replace even needed to modify the YouTube videold to conform with the format of the Internet Archive identifier?

info on YT videold :
"Thus, the maximally-constrained regular expression (RegEx) for the videoId would be as follows:
[0-9A-Za-z_-]{10}[048AEIMQUYcgkosw] "

(https://webapps.stackexchange.com/questions/54443/format-for-id-of-youtube-video)
========
info on IA identifier:
accepted values: String, minimum length is 5 characters, maximum length is 100 characters, contains only Roman alphabet characters, numbers, periods (.), underscores ( _ ), or dashes ( - ), and first character must be alphanumeric. mediatype:account items begin with @ symbol. "

(https://archive.org/services/docs/api/metadata-schema/index.html)

disclaimer: i am a hobbyist programmer and my suggestions should be double-checked

**Comment by brandongalbraith** [comment]
I am currently unavailable but will provide context as to the previous fix
implementation shortly. I understand this is currently breaking and will
prioritize.

**Comment by vxbinaca** [comment]
Medium priority. It's occasionally and in rare cases double uploading with slightly different item IDs.

**Comment by vxbinaca** [comment]
@altCensored Untrack the following creators from your site please (they're taken care of by me, and trying to gather up with 5 people their copies of the videos is tedious):

- Tommy Robinson (5 of you all are fighting to back this up and my scripts track it, it's taken care of)
- Lauren Southern (5 of you all are fighting to back this up and my scripts track it, it's taken care of)
- Sargon Of Akkad and his 3 other channels (he has a collection [here](https://archive.org/details/sargonyoutube))
- Vee and his 2 other channels (he has a collection [here](https://archive.org/details/veevideos))
- Louis La Vau and his single backup channel (he has a collection [here](https://archive.org/details/louislevauvideos))

These subjects are re-checked hourly on my server. New videos re added to the collection and journaled so it doesn't get-download them. If your scripts slip in before me and get it it fucks my shit up.

Try to take a look at [my other collections[(https://archive.org/details/@vxbinaca&tab=collections) and take note of the subjects I track.

My email is vxbinaca@gmail.com. Let's co-ordinate and not have to do a lot of work getting things moved around and we can get along. I'm a easy guy to get along with if you don't step on my toes.

**Comment by BlueCatYellowCat** [comment]
For anyone who wishes to fix this: please note that a similar related issue occurs when archiving a video with an ID containing multiple '-' in a row:

`https://youtube.com/watch?v=_--M04_mN-M` --> `https://archive.org/details/youtube-_-M04_mN-M`

Notice that the second URL turns '--' into '-'

**Comment by vxbinaca** [comment]
I'm very leery of playing with that code because of how Brad's fixes gives us Twitter and Twitch uploads. But thanks @BlueCatYellowCat for the insight.

**Comment by vxbinaca** [comment]
I am going to keep this issue open with the caveat:

We cannot reduce site support. That is not a option. This is a moderate severity bug. The fix cannot break compatibility shims Brad put in for Archive.org item names. If it's going to break item name compatability you can forget even issuing a PR I won't accept it. The internet is larger than youtube and this is a minor bug.

**Comment by brandongalbraith** [comment]
I totally dropped the ball on this. I will work on it tonight and improve
the tests for parsing IDs.

**Comment by vxbinaca** [comment]
No you didn't you squashed a bug and it was needed. This is just a weird side effect and might not even be yours.

**Comment by rudolphos** [comment]
@vxbinaca speaking of co-ordination, why archive staff sometimes make items 'dark' (taken offline)?

Is that a request by author himself or some other reasons?

![image](https://user-images.githubusercontent.com/4366810/59943249-68f76a00-946a-11e9-9573-dacfc1aa8598.png)

**Comment by brandongalbraith** [comment]
@rudolphos You will want to contact the Internet Archive as to why items are darked. There are various reasons this may occur, but is out of scope here.

**Comment by vxbinaca** [comment]
We're not Archive.org staff @rudolphos make a separate issue next time.

**Comment by vxbinaca** [comment]
@rudolphos those particular items were darked at my request because the creator - 1791L - kept hammering my uploads with takedown requests. So I requested my uploads of his content be removed.

Since you like to upload right-wing content I suggest you not upload 1791L and you tell the others in your chat the same thing.

**Comment by altCensored** [comment]
congrats and thank you to the contributors who did all the recent work on the new release.

of course i realize the issue is still marked as open or i would not be able to post this reply :)
i did just test to confirm that the problem is still there by re-uploading 'https://www.youtube.com/watch?v=-hbo--2V-yk'.

IA item https://archive.org/details/youtube-hbo-2V-yk was updated (note file dates on 'show all files': https://archive.org/download/youtube-hbo-2V-yk), instead of item https://archive.org/details/youtube--hbo--2V-yk (file details: https://archive.org/download/youtube--hbo--2V-yk).

i understand that this goes back to issue [#59](https://github.com/bibanon/tubeup/pull/59), and is talked about during all the recent work on issue [Fix #121 with proper elif #123](https://github.com/bibanon/tubeup/pull/123).

in my opinion it is important and i do believe it should be fixed.

the reason i believe this is that YT is still the largest video platform on the planet, and IA has become a repository for many YT videos, some of which are only available if the correct IA url with the correct YT identifier is known.

jsut my two cents, please let me know how i can contribute to fixing this problem, and txs again for a great tool!

**Comment by vxbinaca** [comment]
@altCensored check your emails your scripts are stealing the videos I upload you're interfering with my projects, specifically Sargon Of Akkad and others. Please get in touch with my email, I sent you one months ago.

**Comment by altCensored** [comment]
@ XXLuigiMario thank-you very much for this fix and thereby making all future uploads by anyone using tubeup conform to the original YouTube identifier. i was not able to fix it, and was using a modified personal version that did fix it solely for uploading YT videos.

anyone with the original YT id can look for the video on the Internet Archive using the standard syntax of:
https://archive.org/details/youtube-eiShY7m6Kk0

altCensored.com (currently with 1.2M+ YouTube metadata video and 8K+ channel records) does exactly that when we detect one of those 8K+ channels as removed or self-censored.

Using the list of YT id´s associated with the channel we check on IA if the video has been archived, then flag it as available and feature it on altCen.

a sincere thanks to all the contributors who have made this great tool available, and of course the generous ongoing support of IA.

ps - the altCen front-end (Flask/python) is open source and we wold love to add an API to the Postgres back-end:
https://gitlab.com/altCensored.com/altcensored/-/issues/3
