### ISSUE TITLE
Not enough disk space on my system

### ISSUE THREAD

**Issue by 12221222** [bibanon/tubeup#97]
```
OSError: [Errno 28] No space left on device
```

Obviously the disk space problem is not your fault, but why do the videos need to all be downloaded before they are all uploaded? I would not have this problem if the videos were downloaded and uploaded in smaller groups (maybe ten or twenty), but now I have 100 GB of video on my computer and cannot upload any of it because of #82.

**Comment by brandongalbraith** [comment]
I’m currently evaluating solutions for this problem (local artifact
management pre and post archival).

**Comment by vxbinaca** [comment]
Rip the videos one by one. Also before you use it again delete the contents of `~/.tubeup/downloads/`

**Comment by vxbinaca** [comment]
@12221222 also I would advise you think hard about what your ripping to make sure it's really endangered and you're not just dumping parts of youtube onto IA. They're a non-profit. So think before you do large rips

**Comment by vxbinaca** [comment]
Also you're hiding what rips failed I really should close this issue but I'm feeling charitable today. I would appreciate a example of what failed. 

I'm giving you 24 hours before I close this issue to cough up some error logs of rips failing. Not of a disk error that's a symptom I want the Tubeup errors with uncensored output. 

Please do not just wildly dump onto IA in the future.

**Comment by vxbinaca** [comment]
One last comment on this before he either responds or I close it, some insight into the bug:

This happens for two reasons:

1. Something wonky in the handover betweek youtube-dl and uploading happens.
2. During download, a error like a copyright stuck video halts the rip even though we have `--ignore-errors` set as a library call. For some reason, the library calls don't always act like they should when done as flags with a binary. Lazy rippers like the issue opener here just assume everything went up when it didn't and don't watch output to make sure everything is okay. It doesn't help that the erre output *ahem Refeed* isn't the most helpful either.

Now there is a process of finding out what was missed and uploading it, but it's tedious. But I can be done without a mass-delete but the delete is easier.

Ask and I'll try to help.

**Comment by 12221222** [comment]
Yeah I will probably stop archiving the channel, I didn't realized that the user had uploaded hundreds of videos. Sorry about that.

Most of the output is gone because the system deleted it due to low disk space. Here's some of it.

```
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_58M_@_AMN38_U-6EqFAssBB0M.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_58M_@_AMN38_U-6EqFAssBB0M.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/CTB_E_8486_@_22-Dbv_LEuyRLY.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/CTB_E_8486_@_22-Dbv_LEuyRLY.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_3M_@_ATR225_K-KDqZp_ZDDbc.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_3M_@_ATR225_K-KDqZp_ZDDbc.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_249X_@_ATR379_L-8gM9gjtZLiM.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_249X_@_ATR379_L-8gM9gjtZLiM.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_70S_@_ASU11_L-l_IW0jk97KM.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_70S_@_ASU11_L-l_IW0jk97KM.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_277X_@_ATENU1085_S-71iqe3_L2cQ.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_277X_@_ATENU1085_S-71iqe3_L2cQ.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_276P_@_AP78_U-dXER_ehI7WY.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_276P_@_AP78_U-dXER_ehI7WY.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_58M_@_APM1_U-3vyOxJ5gj7k.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_58M_@_APM1_U-3vyOxJ5gj7k.description'

video doesn't have subtitles
ERROR: Cannot write description file /Users/home/.tubeup/downloads/KMB_74A_@_AMC1_K-0i-n640eBfU.description
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1776, in process_info
    with io.open(encodeFilename(descfn), 'w', encoding='utf-8') as descfile:
OSError: [Errno 28] No space left on device: '/Users/home/.tubeup/downloads/KMB_74A_@_AMC1_K-0i-n640eBfU.description'
```

**Comment by vxbinaca** [comment]
No that's not what I'm looking for. Again we need the error that caused your rips to fail not the storage error. 

Closing.

In the future only mirror endangered content, and do it one video at a time unless it's an emergency. Read the front page again from top to bottom. Pay attention to the part where you should alert staff to the channel you're dumping and why you're dumping it. Don't just say "I want a copy of it just in case". Again only dump endangered content you can specifically articulate why it's in danger.

**Comment by vxbinaca** [comment]
Also why does it have to download the whole channel before uploading it? Because you're ripping a whole channel that's why.

**Comment by makeworld-the-better-one** [comment]
If anyone's still looking at this, [here's](https://old.reddit.com/r/JustArchivistThings/comments/80wua3/archiving_youtube_videos_archiveorg_tubeup/) a Reddit post with code that will use `tubeup` to archive a channel/playlist, but download each video individually. I'd caution that the post may be outdated, I didn't write it and I haven't tested it.

**Comment by vxbinaca** [comment]
We're fine on this. Don't rip channels unless it's a emergency. Use a VPS to rip.
