### ISSUE TITLE
Message to indicate possibility of upload being marked as spam.

### ISSUE THREAD

**Issue by Basillica85** [bibanon/tubeup#98]
A message or warning that's thrown up when 503 Slow Down Spam errors are detected, or is simply a preemptive warning that if certain videos retry indefinitely while others upload perfectly fine, it's possible that they've been marked as spam (rather than there being a bandwidth issue), and that Archive.org needs to be contacted to fix it.

This would prevent the creation of redundant issues about videos failing to upload for long periods of time, while directing them to a solution before coming here.

**Comment by vxbinaca** [comment]
I'll just keep closing them if you all in your chat keep making them. This isn't our problem we can't correct for it that's been said in every issue. You won't talk to IA.

**Comment by Basillica85** [comment]
I'm not affiliated with any of those people. I was just making a suggestion to save yourself some headache. I only realized my upload was marked as spam when I tried uploading manually and it gave a 503 spam error, and I contacted the people at archive.org to fix it.
I'm truly sorry if I wasted your time.

**Comment by vxbinaca** [comment]
Paste the error. You made a issue with no command or output. How am I supposed to troubleshoot your issue when you obscure what you did?

**Comment by Basillica85** [comment]
I simply typed 'tubeup URL'. I got a response from archive.org and I was able to finish the upload. I was just making a suggestion to add a message somewhere that if the video doesn't upload, it's possible that the upload was marked as spam.

**Comment by vxbinaca** [comment]
One last chance. Command a d output that generated the error or I lock this issue.

**Comment by vxbinaca** [comment]
If you want that feature submit a PR. Since you're making suggestions on something that you don't understand how it works, why not give us the command and output you ran so we can test it for ourselves.

**Comment by Basillica85** [comment]
The command was "uptube https://www.youtube.com/watch?v=80zxVuxAVL8", but it can't be replicated because I had contacted archive.org to fix it being marked as spam (the output was the standard retrying message).
I do understand why it happens, and I won't waste any more of your time.

**Comment by vxbinaca** [comment]
Okay when you uploaded it, what specifically was the 503 error? Paste it. Don't describe it. I want console output.

**Comment by vxbinaca** [comment]
Okay I looked into your item. It's complete, not snapped off, looks like it hasn't been fooled with in its history. 

Sometimes IA, who I'll remind you is a non-profit, has server issues. You work through them when they happen or preferably report them to us *with command and full output from the time the command was run to failure*. 

Also yeah I'd agree with staff dumping a bunch of LucasArts LPs that definitely not in danger of being erased is spammy. Is this content 8n danger of being erased, or do you just want it copied else where? If the later, consider youtube-dl and your hard drive.
